# Features, Labels, Dataset Structure, X and y

In [3]:
!pip install numpy pandas matplotlib seaborn

Requirement already satisfied: numpy in .\venv15\Lib\site-packages (2.4.6)
Requirement already satisfied: pandas in .\venv15\Lib\site-packages (3.0.3)
Requirement already satisfied: matplotlib in .\venv15\Lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in .\venv15\Lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv15\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv15\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in .\venv15\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\venv15\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\venv15\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\venv15\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\venv15\Lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in .\venv15\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\venv15\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in .\venv15\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Dataset

In [5]:
data={
     "Student_id":[1,2,3,4],
     "Study_hours":[8,2,6,3],
     "Attendance":[90,45,80,50],
     "Previous_marks":[85,40,72,45],
     "Final_result":['Pass','Fail','Pass','Fail']
}
df=pd.DataFrame(data)
df

   Student_id  Study_hours  Attendance  Previous_marks Final_result
0           1            8          90              85         Pass
1           2            2          45              40         Fail
2           3            6          80              72         Pass
3           4            3          50              45         Fail

## Features

In [6]:
x=df[["Study_hours","Attendance","Previous_marks"]]
x

   Study_hours  Attendance  Previous_marks
0            8          90              85
1            2          45              40
2            6          80              72
3            3          50              45

## Labels

In [7]:
y=df["Final_result"]
y

0    Pass
1    Fail
2    Pass
3    Fail
Name: Final_result, dtype: str

## Features and Label Together

In [8]:
df1=df[["Study_hours","Attendance","Previous_marks","Final_result"]]
df1

   Study_hours  Attendance  Previous_marks Final_result
0            8          90              85         Pass
1            2          45              40         Fail
2            6          80              72         Pass
3            3          50              45         Fail

## x and y in ML

In [9]:
df1=df.drop("Final_result",axis=1)
df1

   Student_id  Study_hours  Attendance  Previous_marks
0           1            8          90              85
1           2            2          45              40
2           3            6          80              72
3           4            3          50              45

In [10]:
y

0    Pass
1    Fail
2    Pass
3    Fail
Name: Final_result, dtype: str

## Datset Student Placement Prediction

In [11]:
d2={
     "CGPA":[8.7,6.2,7.8,5.8],
     "DSA_score":[85,40,70,35],
     "Projects":[4,1,3,0],
     "Internship":["Yes","No","Yes","No"],
     "Communication_score":[80,55,75,45],
     "Placed":["Yes","No","Yes","No"]
}

In [13]:
df2=pd.DataFrame(d2)
df2

   CGPA  DSA_score  Projects Internship  Communication_score Placed
0   8.7         85         4        Yes                   80    Yes
1   6.2         40         1         No                   55     No
2   7.8         70         3        Yes                   75    Yes
3   5.8         35         0         No                   45     No

## Separate Feature and Label

In [15]:
X = df2[["CGPA", "DSA_score", "Projects", "Internship", "Communication_score"]]
y = df2["Placed"]

print("Features:")
print(X)

print("Label:")
print(y)

Features:
   CGPA  DSA_score  Projects Internship  Communication_score
0   8.7         85         4        Yes                   80
1   6.2         40         1         No                   55
2   7.8         70         3        Yes                   75
3   5.8         35         0         No                   45
Label:
0    Yes
1     No
2    Yes
3     No
Name: Placed, dtype: str

In [17]:
x1=df2.drop("Placed",axis=1)
y1=df2["Placed"]

In [18]:
print(x1)
print(y1)

   CGPA  DSA_score  Projects Internship  Communication_score
0   8.7         85         4        Yes                   80
1   6.2         40         1         No                   55
2   7.8         70         3        Yes                   75
3   5.8         35         0         No                   45
0    Yes
1     No
2    Yes
3     No
Name: Placed, dtype: str

## Check Shape

In [19]:
print(x1.shape)
print(y1.shape)

(4, 5)
(4,)

## Data Leakage Basics

In [20]:
d3={
     "CGPA":[8.7,6.2],
     "DSA_score":[85,40],
     "Final_Interview_Result":['Selected','Rejected'],
     "Placed":['Yes','No']
}

In [22]:
df3=pd.DataFrame(d3)
df3

   CGPA  DSA_score Final_Interview_Result Placed
0   8.7         85               Selected    Yes
1   6.2         40               Rejected     No