# day6_employee_groupby_summary

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in .\venv6\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in .\venv6\Lib\site-packages (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv6\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv6\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\venv6\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## Dataset

In [3]:
import pandas as pd

data = {
    "employee_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "name": ["Amit", "Riya", "Karan", "Neha", "Vikas", "Anjali", "Rohit", "Priya"],
    "salary": [25000, 45000, 80000, 120000, 35000, 70000, 30000, 95000],
    "experience": [1, 3, 6, 8, 2, 5, 1, 7],
    "rating": [3, 4, 5, 5, 2, 4, 3, 5],
    "department": ["HR", "IT", "AI", "AI", "SALES", "DATA", "IT", "DATA"],
    "level": ["Junior", "Mid-Level", "Senior", "Senior", "Junior", "Senior", "Junior", "Senior"]
}

df = pd.DataFrame(data)
df

   employee_id    name  salary  experience  rating department      level
0          101    Amit   25000           1       3         HR     Junior
1          102    Riya   45000           3       4         IT  Mid-Level
2          103   Karan   80000           6       5         AI     Senior
3          104    Neha  120000           8       5         AI     Senior
4          105   Vikas   35000           2       2      SALES     Junior
5          106  Anjali   70000           5       4       DATA     Senior
6          107   Rohit   30000           1       3         IT     Junior
7          108   Priya   95000           7       5       DATA     Senior

### 1. Average salary by department

In [4]:
avg_sal=df.groupby("department")["salary"].mean()
avg_sal

department
AI       100000.0
DATA      82500.0
HR        25000.0
IT        37500.0
SALES     35000.0
Name: salary, dtype: float64

### 2. Highest salary by department

In [5]:
high_sal=df.groupby("department")["salary"].max()
high_sal

department
AI       120000
DATA      95000
HR        25000
IT        45000
SALES     35000
Name: salary, dtype: int64

### 3. Lowest salary by department

In [8]:
low_sal=df.groupby("department")["salary"].min()
low_sal

department
AI       80000
DATA     70000
HR       25000
IT       30000
SALES    35000
Name: salary, dtype: int64

### 4. Employee count by department

In [12]:
emp_count=df.groupby("department")["employee_id"].count()
emp_count

department
AI       2
DATA     2
HR       1
IT       2
SALES    1
Name: employee_id, dtype: int64

## 5. Average rating by level

In [15]:
avg_rating=df.groupby("level")["rating"].mean()
avg_rating.round(3)

level
Junior       2.667
Mid-Level    4.000
Senior       4.750
Name: rating, dtype: float64

### 6. Average experience by level

In [17]:
avg_exp=df.groupby("level")["experience"].mean()
avg_exp

level
Junior       1.333333
Mid-Level    3.000000
Senior       6.500000
Name: experience, dtype: float64

### 7. Salary summary by department using agg()

In [20]:
sal_sum=df.groupby("department")["salary"].agg(["mean","max","min","count"])
sal_sum

                mean     max    min  count
department
AI          100000.0  120000  80000      2
DATA         82500.0   95000  70000      2
HR           25000.0   25000  25000      1
IT           37500.0   45000  30000      2
SALES        35000.0   35000  35000      1

### 8. Group by department and level

In [21]:
dep_lev=df.groupby(["department","level"])["employee_id"].count()
dep_lev

department  level
AI          Senior       2
DATA        Senior       2
HR          Junior       1
IT          Junior       1
            Mid-Level    1
SALES       Junior       1
Name: employee_id, dtype: int64

## 9. Convert grouped output to DataFrame using reset_index()

In [22]:
report=dep_lev.reset_index()
report

  department      level  employee_id
0         AI     Senior            2
1       DATA     Senior            2
2         HR     Junior            1
3         IT     Junior            1
4         IT  Mid-Level            1
5      SALES     Junior            1

### 10. Save summary to CSV

In [23]:
df.to_csv("day6_employee_groupby_summary.csv",index=False)