# 01_pandas_intro.py

In [1]:
import pandas as pd

## Task 1
Create a Pandas Series for marks:
```
[85, 90, 78, 92, 88]
```
Print the full Series.

In [3]:
marks=pd.DataFrame([85,90,78,92,88],columns=["Marks"])
marks

   Marks
0     85
1     90
2     78
3     92
4     88

## Task 2
Create a Series with custom index:
```
Math = 85
Science = 90
English = 78
Computer = 95
```
Print each subject mark separately.

In [5]:
sub=["Maths","Science","English","Computer"]
marks=pd.Series([85,90,78,92],index=sub)
marks

Maths       85
Science     90
English     78
Computer    92
dtype: int64

## Task 3
Create a DataFrame with this data:
```
Name: Pratyaksh, Rahul, Sneha, Aman
Math: 85, 70, 90, 95
Science: 88, 75, 95, 92
English: 78, 80, 92, 88
```
Print the full DataFrame.

In [7]:
df=pd.DataFrame(
     {
          "Name":["Alice","Bob","Charlie","David","Eve"],
          "Maths":[85,90,78,92,88],
          "Science":[80,85,82,88,90],
          "English":[78,82,80,85,87]
     }
)
df

      Name  Maths  Science  English
0    Alice     85       80       78
1      Bob     90       85       82
2  Charlie     78       82       80
3    David     92       88       85
4      Eve     88       90       87

Task 4
Print:
```
First 2 rows
Last 2 rows
Shape
Columns
Only Name column
Name and Math columns

In [8]:
df.head(2)

    Name  Maths  Science  English
0  Alice     85       80       78
1    Bob     90       85       82

In [9]:
df.tail(2)

    Name  Maths  Science  English
3  David     92       88       85
4    Eve     88       90       87

In [11]:
df.shape

(5, 4)

In [12]:
df.columns

Index(['Name', 'Maths', 'Science', 'English'], dtype='str')

In [13]:
df["Name"]

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: str

In [16]:
df[["Name","Maths"]]

      Name  Maths
0    Alice     85
1      Bob     90
2  Charlie     78
3    David     92
4      Eve     88