# 03_selection_filtering.py

## Task 1
Read:
```
student_performance.csv
```
Print the full dataset.

In [2]:
import pandas as pd
# Load the dataset
df = pd.read_csv("student_performance.csv")
df

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
1           2      Rahul    70       75       80          85            3
2           3      Sneha    90       95       92          96            6
3           4       Aman    95       92       88          90            7
4           5      Priya    60       75       80          80            4
5           6      Rohit    45       55       50          70            2
6           7       Neha    88       84       90          94            5
7           8      Karan    35       40       45          60            1

## Task 2
Select and print:
```
Name column
Math column
Name and Attendance columns
Name, Math, Science, English columns

In [3]:
df["Name"]

0    Pratyaksh
1        Rahul
2        Sneha
3         Aman
4        Priya
5        Rohit
6         Neha
7        Karan
Name: Name, dtype: str

In [4]:
df["Math"]

0    85
1    70
2    90
3    95
4    60
5    45
6    88
7    35
Name: Math, dtype: int64

In [7]:
df[["Name","Attendance"]]

        Name  Attendance
0  Pratyaksh          92
1      Rahul          85
2      Sneha          96
3       Aman          90
4      Priya          80
5      Rohit          70
6       Neha          94
7      Karan          60

In [8]:
df[["Name", "Math","Science","English"]]

        Name  Math  Science  English
0  Pratyaksh    85       88       78
1      Rahul    70       75       80
2      Sneha    90       95       92
3       Aman    95       92       88
4      Priya    60       75       80
5      Rohit    45       55       50
6       Neha    88       84       90
7      Karan    35       40       45

In [9]:
df.iloc[0]

Student_ID             1
Name           Pratyaksh
Math                  85
Science               88
English               78
Attendance            92
Study_Hours            5
Name: 0, dtype: object

In [10]:
df.iloc[0:3]

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
1           2      Rahul    70       75       80          85            3
2           3      Sneha    90       95       92          96            6

In [11]:
df.iloc[2,1]

'Sneha'

In [12]:
df.iloc[3,2]

np.int64(95)

## Task 4
Using filtering, print:
```
Students with Math > 80
Students with Attendance > 90
Students with Study_Hours > 4
Students with Math > 80 and Attendance > 90
Students with Math > 90 or Science > 90

In [14]:
math_scores = df[df["Math"] > 80]
math_scores

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
2           3      Sneha    90       95       92          96            6
3           4       Aman    95       92       88          90            7
6           7       Neha    88       84       90          94            5

In [15]:
attend=df[df["Attendance"] >90]
attend

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
2           3      Sneha    90       95       92          96            6
6           7       Neha    88       84       90          94            5

In [17]:
study_hrs=df[df["Study_Hours"] > 4]
study_hrs

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
2           3      Sneha    90       95       92          96            6
3           4       Aman    95       92       88          90            7
6           7       Neha    88       84       90          94            5

In [18]:
res1 = df[(df["Math"] > 80) & (df["Attendance"] > 90)]
res1

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
2           3      Sneha    90       95       92          96            6
6           7       Neha    88       84       90          94            5

In [20]:
res2 = df[(df["Math"] > 90) | (df["Science"] > 90)]
res2

   Student_ID   Name  Math  Science  English  Attendance  Study_Hours
2           3  Sneha    90       95       92          96            6
3           4   Aman    95       92       88          90            7

Task 5
Create:
```
Total column
Average column
Result column
Grade column
```
Then separate:
```
X = Math, Science, English, Attendance, Study_Hoursy = Result
```
---

In [22]:
df["Total_Score"] = df["Math"] + df["Science"] + df["English"]

In [23]:
df["Average_Score"] = df["Total_Score"] / 3
df["Avg"]=df["Average_Score"].round(2)

In [24]:
df["Result"]=["Pass" if x >= 60 else "Fail" for x in df["Avg"]]

In [25]:
def assign_grades(avg):
     if avg >= 90:
          return "A"
     elif avg >= 80:
          return "B"
     elif avg >= 70:
          return "C"
     elif avg >= 60:
          return "D"
     else:
          return "Fail"
df["Grade"] = df["Avg"].apply(assign_grades)

In [28]:
df

,Student_ID,Name,Math,Science,English,Attendance,Study_Hours,Total_Score,Average_Score,Avg,Result,Grade
0,1,Pratyaksh,85,88,78,92,5,251,83.666667,83.67,Pass,B
1,2,Rahul,70,75,80,85,3,225,75.000000,75.00,Pass,C
2,3,Sneha,90,95,92,96,6,277,92.333333,92.33,Pass,A
3,4,Aman,95,92,88,90,7,275,91.666667,91.67,Pass,A
4,5,Priya,60,75,80,80,4,215,71.666667,71.67,Pass,C
5,6,Rohit,45,55,50,70,2,150,50.000000,50.00,Fail,Fail
6,7,Neha,88,84,90,94,5,262,87.333333,87.33,Pass,B
7,8,Karan,35,40,45,60,1,120,40.000000,40.00,Fail,Fail

In [29]:
x=df[["Math","Science","English"]]
y=df["Result"]
print(x)
print(y)

   Math  Science  English
0    85       88       78
1    70       75       80
2    90       95       92
3    95       92       88
4    60       75       80
5    45       55       50
6    88       84       90
7    35       40       45
0    Pass
1    Pass
2    Pass
3    Pass
4    Pass
5    Fail
6    Pass
7    Fail
Name: Result, dtype: str