# Introduction to Pandas + Series and DataFrame

## Installing Pandas

### Install pandas

In [2]:
!pip install pandas

Requirement already satisfied: pandas in .\venv3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in .\venv3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\venv3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### Check Installation

In [4]:
import pandas as pd
print(pd.__version__)

3.0.3

## Pandas Series

In [5]:
import pandas as pd
marks = pd.Series([85, 90, 78, 92])
print(marks)

0    85
1    90
2    78
3    92
dtype: int64

## Series with Custom Index

In [6]:
import pandas as pd
marks = pd.Series(
    [85, 90, 78],
    index=["Math", "Science", "English"]
)
print(marks)

Math       85
Science    90
English    78
dtype: int64

### Accessing Series Vales

In [8]:
import pandas as pd
marks = pd.Series(
    [85, 90, 78],
    index=["Math", "Science", "English"]
)
for i in range(len(marks)):
     print(f"{marks.index[i]}: {marks.iloc[i]}")

Math: 85
Science: 90
English: 78

In [11]:
print(marks["Math"])
print(marks["English"])
print(marks["Science"])

85
78
90

## 7. AI/ML Use CAse

In [12]:
import pandas as pd
study_hours = pd.Series([2, 4, 6, 8, 10])
print(study_hours)

0     2
1     4
2     6
3     8
4    10
dtype: int64

## Pandas Data frame

In [13]:
import pandas as pd
data = {
    "Name": ["Pratyaksh", "Rahul", "Sneha"],
    "Math": [85, 70, 90],
    "Science": [88, 75, 95],
    "English": [78, 80, 92]
}
df = pd.DataFrame(data)
print(df)

        Name  Math  Science  English
0  Pratyaksh    85       88       78
1      Rahul    70       75       80
2      Sneha    90       95       92

## Checking Data frame Columns:

In [14]:
import pandas as pd
data = {
    "Name": ["Pratyaksh", "Rahul", "Sneha"],
    "Math": [85, 70, 90],
    "Science": [88, 75, 95],
    "English": [78, 80, 92]
}
df = pd.DataFrame(data)
print(df.columns)

Index(['Name', 'Math', 'Science', 'English'], dtype='str')

## Checking Data Frame Shape:

In [15]:
print(df.shape)

(3, 4)

## Checking First Rows using `head()`

In [16]:
print(df.head(2))

        Name  Math  Science  English
0  Pratyaksh    85       88       78
1      Rahul    70       75       80

## Checking Last Row using `tail()`

In [18]:
print(df.tail(1))

    Name  Math  Science  English
2  Sneha    90       95       92

## Selecting One Column

In [19]:
print(df["Name"])

0    Pratyaksh
1        Rahul
2        Sneha
Name: Name, dtype: str

## Selecting Multiple Columns

In [20]:
print(df[["Name", "Math"]])

        Name  Math
0  Pratyaksh    85
1      Rahul    70
2      Sneha    90

## Creating New Column

In [21]:
df["Total"] = df["Math"] + df["Science"] + df["English"]
print(df)

        Name  Math  Science  English  Total
0  Pratyaksh    85       88       78    251
1      Rahul    70       75       80    225
2      Sneha    90       95       92    277

## 17. Creating Average Column

In [23]:
df["Average"] = df["Total"] / 3
df

        Name  Math  Science  English  Total    Average
0  Pratyaksh    85       88       78    251  83.666667
1      Rahul    70       75       80    225  75.000000
2      Sneha    90       95       92    277  92.333333

To round off avergaes:

In [25]:
df["Average"]= df["Average"].round(2)
df

        Name  Math  Science  English  Total  Average
0  Pratyaksh    85       88       78    251    83.67
1      Rahul    70       75       80    225    75.00
2      Sneha    90       95       92    277    92.33

## 18. Adding Result Column

In [27]:
df["Result"]=["Pass" if avg >= 50 else "Fail" for avg in df["Average"]]
df

        Name  Math  Science  English  Total  Average Result
0  Pratyaksh    85       88       78    251    83.67   Pass
1      Rahul    70       75       80    225    75.00   Pass
2      Sneha    90       95       92    277    92.33   Pass

## Common Errors:

## Error:

In [28]:
df = DataFrame(data)

NameError: name 'DataFrame' is not defined

In [ ]:
print(df["math"])

In [ ]:
print(df["Name", "Math"])

In [ ]:
data = {
    "Name": ["Pratyaksh", "Rahul", "Sneha"],
    "Math": [85, 70]
}
df = pd.DataFrame(data)