# Reading CSV Files + Dataset Exploration

In [1]:
import pandas as pd

## Reading CSV file using Pandas

In [3]:
df1=pd.read_csv("Student_performance.csv")
df1

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
1           2      Rahul    70       75       80          85            3
2           3      Sneha    90       95       92          96            6
3           4       Aman    95       92       88          90            7
4           5      Priya    60       75       80          80            4
5           6      Rohit    45       55       50          70            2
6           7       Neha    88       84       90          94            5
7           8      Karan    35       40       45          60            1

## Display First Rows using head()

In [5]:
df1.head()

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
1           2      Rahul    70       75       80          85            3
2           3      Sneha    90       95       92          96            6
3           4       Aman    95       92       88          90            7
4           5      Priya    60       75       80          80            4

## Display Last Rows using tail()

In [6]:
df1.tail()

   Student_ID   Name  Math  Science  English  Attendance  Study_Hours
3           4   Aman    95       92       88          90            7
4           5  Priya    60       75       80          80            4
5           6  Rohit    45       55       50          70            2
6           7   Neha    88       84       90          94            5
7           8  Karan    35       40       45          60            1

## Checking Shape

In [8]:
print(df1.shape)

(8, 7)

## Checking Columns

In [10]:
df1.columns

Index(['Student_ID', 'Name', 'Math', 'Science', 'English', 'Attendance',
       'Study_Hours'],
      dtype='str')

In [11]:
print(list(df1.columns))

['Student_ID', 'Name', 'Math', 'Science', 'English', 'Attendance', 'Study_Hours']

## 11. Checking Dataset Information using info()

In [13]:
print(df1.info())

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student_ID   8 non-null      int64
 1   Name         8 non-null      str
 2   Math         8 non-null      int64
 3   Science      8 non-null      int64
 4   English      8 non-null      int64
 5   Attendance   8 non-null      int64
 6   Study_Hours  8 non-null      int64
dtypes: int64(6), str(1)
memory usage: 580.0 bytes
None

## Checking Statistical Summary using describe()

In [15]:
df1.describe()

       Student_ID       Math    Science    English  Attendance  Study_Hours
count     8.00000   8.000000   8.000000   8.000000    8.000000      8.00000
mean      4.50000  71.000000  75.500000  75.375000   83.375000      4.12500
std       2.44949  22.411732  19.131126  17.991565   12.704752      2.03101
min       1.00000  35.000000  40.000000  45.000000   60.000000      1.00000
25%       2.75000  56.250000  70.000000  71.000000   77.500000      2.75000
50%       4.50000  77.500000  79.500000  80.000000   87.500000      4.50000
75%       6.25000  88.500000  89.000000  88.500000   92.500000      5.25000
max       8.00000  95.000000  95.000000  92.000000   96.000000      7.00000

## 13. Checking Data Types

In [20]:
print(df1.dtypes)

Student_ID     int64
Name             str
Math           int64
Science        int64
English        int64
Attendance     int64
Study_Hours    int64
dtype: object

## Checking Missing VAlues

In [21]:
df1.isnull()

   Student_ID   Name   Math  Science  English  Attendance  Study_Hours
0       False  False  False    False    False       False        False
1       False  False  False    False    False       False        False
2       False  False  False    False    False       False        False
3       False  False  False    False    False       False        False
4       False  False  False    False    False       False        False
5       False  False  False    False    False       False        False
6       False  False  False    False    False       False        False
7       False  False  False    False    False       False        False

In [23]:
print(df1.isnull().sum())

Student_ID     0
Name           0
Math           0
Science        0
English        0
Attendance     0
Study_Hours    0
dtype: int64

## Creating Total and Average Columns

In [27]:
df1["Total"] = df1["Math"] + df1["Science"] + df1["English"]
df1["Average"] = df1["Total"] / 3
df1["Average"] = df1["Average"].round(2)
df1

,Student_ID,Name,Math,Science,English,Attendance,Study_Hours,Total,Average
0,1,Pratyaksh,85,88,78,92,5,251,83.67
1,2,Rahul,70,75,80,85,3,225,75.00
2,3,Sneha,90,95,92,96,6,277,92.33
3,4,Aman,95,92,88,90,7,275,91.67
4,5,Priya,60,75,80,80,4,215,71.67
5,6,Rohit,45,55,50,70,2,150,50.00
6,7,Neha,88,84,90,94,5,262,87.33
7,8,Karan,35,40,45,60,1,120,40.00

## Save Update DataFrame to CSV

In [29]:
df1.to_csv("student_performance_updated.csv", index=False)

## Common Errors

### Error 1

In [30]:
df = pd.read_csv("students.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'students.csv'

### Error :

In [31]:
df["math"]

NameError: name 'df' is not defined