# 02_reading_csv_exploration.py

In [3]:
!pip install pandas

Requirement already satisfied: pandas in .\venv4\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in .\venv4\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv4\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv4\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\venv4\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd

## Task 1
Create a CSV file named:
```
student_performance.csv
```
Add the dataset given above.

## Task 2
Read the CSV file using Pandas and print the full DataFrame.

In [5]:
df=pd.read_csv('student_performance.csv')
df

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
1           2      Rahul    70       75       80          85            3
2           3      Sneha    90       95       92          96            6
3           4       Aman    95       92       88          90            7
4           5      Priya    60       75       80          80            4
5           6      Rohit    45       55       50          70            2
6           7       Neha    88       84       90          94            5
7           8      Karan    35       40       45          60            1

## Task 3
Print:
```
First 5 rows
First 3 rows
Last 5 rows
Last 3 rows
Shape
Columns
Data types
```

In [6]:
df.head()

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
1           2      Rahul    70       75       80          85            3
2           3      Sneha    90       95       92          96            6
3           4       Aman    95       92       88          90            7
4           5      Priya    60       75       80          80            4

In [7]:
df.head(3)

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
1           2      Rahul    70       75       80          85            3
2           3      Sneha    90       95       92          96            6

In [8]:
df.tail()

   Student_ID   Name  Math  Science  English  Attendance  Study_Hours
3           4   Aman    95       92       88          90            7
4           5  Priya    60       75       80          80            4
5           6  Rohit    45       55       50          70            2
6           7   Neha    88       84       90          94            5
7           8  Karan    35       40       45          60            1

In [9]:
df.tail(3)

   Student_ID   Name  Math  Science  English  Attendance  Study_Hours
5           6  Rohit    45       55       50          70            2
6           7   Neha    88       84       90          94            5
7           8  Karan    35       40       45          60            1

In [10]:
df.shape

(8, 7)

In [11]:
df.columns

Index(['Student_ID', 'Name', 'Math', 'Science', 'English', 'Attendance',
       'Study_Hours'],
      dtype='str')

In [12]:
print(list(df.columns))

['Student_ID', 'Name', 'Math', 'Science', 'English', 'Attendance', 'Study_Hours']

In [13]:
df.dtypes

Student_ID     int64
Name             str
Math           int64
Science        int64
English        int64
Attendance     int64
Study_Hours    int64
dtype: object

## Task 4
Use:
```
df.info()
df.describe()
df.isnull().sum()

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student_ID   8 non-null      int64
 1   Name         8 non-null      str
 2   Math         8 non-null      int64
 3   Science      8 non-null      int64
 4   English      8 non-null      int64
 5   Attendance   8 non-null      int64
 6   Study_Hours  8 non-null      int64
dtypes: int64(6), str(1)
memory usage: 580.0 bytes

In [15]:
df.describe()

       Student_ID       Math    Science    English  Attendance  Study_Hours
count     8.00000   8.000000   8.000000   8.000000    8.000000      8.00000
mean      4.50000  71.000000  75.500000  75.375000   83.375000      4.12500
std       2.44949  22.411732  19.131126  17.991565   12.704752      2.03101
min       1.00000  35.000000  40.000000  45.000000   60.000000      1.00000
25%       2.75000  56.250000  70.000000  71.000000   77.500000      2.75000
50%       4.50000  77.500000  79.500000  80.000000   87.500000      4.50000
75%       6.25000  88.500000  89.000000  88.500000   92.500000      5.25000
max       8.00000  95.000000  95.000000  92.000000   96.000000      7.00000

In [16]:
df.isnull().sum()

Student_ID     0
Name           0
Math           0
Science        0
English        0
Attendance     0
Study_Hours    0
dtype: int64

## Task 5
Create new columns:
```
Total
Average
```
Then save the updated dataset as:
```
student_performance_updated.csv
```

In [17]:
df['Total Marks'] = df['Math'] + df['Science'] + df['English']
df['Average Marks'] = df['Total Marks'] / 3
df['average_marks'] = df['Average Marks'].round(2)
df

,Student_ID,Name,Math,Science,English,Attendance,Study_Hours,Total Marks,Average Marks,average_marks
0,1,Pratyaksh,85,88,78,92,5,251,83.666667,83.67
1,2,Rahul,70,75,80,85,3,225,75.000000,75.00
2,3,Sneha,90,95,92,96,6,277,92.333333,92.33
3,4,Aman,95,92,88,90,7,275,91.666667,91.67
4,5,Priya,60,75,80,80,4,215,71.666667,71.67
5,6,Rohit,45,55,50,70,2,150,50.000000,50.00
6,7,Neha,88,84,90,94,5,262,87.333333,87.33
7,8,Karan,35,40,45,60,1,120,40.000000,40.00