# Selecting Rows, Columns & Filtering Data

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('student_performance.csv')
df

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
1           2      Rahul    70       75       80          85            3
2           3      Sneha    90       95       92          96            6
3           4       Aman    95       92       88          90            7
4           5      Priya    60       75       80          80            4
5           6      Rohit    45       55       50          70            2
6           7       Neha    88       84       90          94            5
7           8      Karan    35       40       45          60            1

## Selecting One Column

In [4]:
df["Name"]

0    Pratyaksh
1        Rahul
2        Sneha
3         Aman
4        Priya
5        Rohit
6         Neha
7        Karan
Name: Name, dtype: str

## Selecting Multiple Columns

In [5]:
print(df[["Name", "Math", "Science"]])

        Name  Math  Science
0  Pratyaksh    85       88
1      Rahul    70       75
2      Sneha    90       95
3       Aman    95       92
4      Priya    60       75
5      Rohit    45       55
6       Neha    88       84
7      Karan    35       40

## Selecting ROws using `iloc`

In [6]:
df.iloc[0]

Student_ID             1
Name           Pratyaksh
Math                  85
Science               88
English               78
Attendance            92
Study_Hours            5
Name: 0, dtype: object

### Selecting multiple rows

In [7]:
df.iloc[0:3]

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
1           2      Rahul    70       75       80          85            3
2           3      Sneha    90       95       92          96            6

## Selecting Specific Row and Column using iloc

In [8]:
df.iloc[0,1]

'Pratyaksh'

In [9]:
print(df.iloc[2, 2])

90

## Selecting Rows using loc

In [10]:
print(df.loc[0])

Student_ID             1
Name           Pratyaksh
Math                  85
Science               88
English               78
Attendance            92
Study_Hours            5
Name: 0, dtype: object

### Selecting Specific Column with loc

In [11]:
print(df.loc[:, "Name"])

0    Pratyaksh
1        Rahul
2        Sneha
3         Aman
4        Priya
5        Rohit
6         Neha
7        Karan
Name: Name, dtype: str

### Selecting Multiple Columns with `loc`

In [12]:
print(df.loc[:, ["Name", "Math", "Science"]])

        Name  Math  Science
0  Pratyaksh    85       88
1      Rahul    70       75
2      Sneha    90       95
3       Aman    95       92
4      Priya    60       75
5      Rohit    45       55
6       Neha    88       84
7      Karan    35       40

## Difference between loc and iloc

In [13]:
df.iloc[0, 1]

'Pratyaksh'

In [14]:
df.loc[0, "Name"]

'Pratyaksh'

## Filtering Data

In [15]:
high_math = df[df["Math"] > 80]
print(high_math)

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
2           3      Sneha    90       95       92          96            6
3           4       Aman    95       92       88          90            7
6           7       Neha    88       84       90          94            5

## Filter Students with Attendance Above 90

In [16]:
high_attendance = df[df["Attendance"] > 90]
print(high_attendance)

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
2           3      Sneha    90       95       92          96            6
6           7       Neha    88       84       90          94            5

## Filter Students with Study Hours More Than 4

In [17]:
hardworking_students = df[df["Study_Hours"] > 4]
print(hardworking_students)

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
2           3      Sneha    90       95       92          96            6
3           4       Aman    95       92       88          90            7
6           7       Neha    88       84       90          94            5

## 13. Multiple Conditions

In [18]:
result = df[(df["Math"] > 80) & (df["Attendance"] > 90)]
print(result)

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours
0           1  Pratyaksh    85       88       78          92            5
2           3      Sneha    90       95       92          96            6
6           7       Neha    88       84       90          94            5

In [19]:
result = df[(df["Math"] > 90) | (df["Science"] > 90)]
print(result)

   Student_ID   Name  Math  Science  English  Attendance  Study_Hours
2           3  Sneha    90       95       92          96            6
3           4   Aman    95       92       88          90            7

## Creating Total and Average Columns

In [20]:
df["Total"] = df["Math"] + df["Science"] + df["English"]
df["Average"] = df["Total"] / 3
df["Average"] = df["Average"].round(2)
df

,Student_ID,Name,Math,Science,English,Attendance,Study_Hours,Total,Average
0,1,Pratyaksh,85,88,78,92,5,251,83.67
1,2,Rahul,70,75,80,85,3,225,75.00
2,3,Sneha,90,95,92,96,6,277,92.33
3,4,Aman,95,92,88,90,7,275,91.67
4,5,Priya,60,75,80,80,4,215,71.67
5,6,Rohit,45,55,50,70,2,150,50.00
6,7,Neha,88,84,90,94,5,262,87.33
7,8,Karan,35,40,45,60,1,120,40.00

## Filter Passed Students
Pass condition:

Average >= 50

In [21]:
passed_students = df[df["Average"] >= 50]
print(passed_students)

   Student_ID       Name  Math  Science  English  Attendance  Study_Hours  \
0           1  Pratyaksh    85       88       78          92            5
1           2      Rahul    70       75       80          85            3
2           3      Sneha    90       95       92          96            6
3           4       Aman    95       92       88          90            7
4           5      Priya    60       75       80          80            4
5           6      Rohit    45       55       50          70            2
6           7       Neha    88       84       90          94            5

   Total  Average
0    251    83.67
1    225    75.00
2    277    92.33
3    275    91.67
4    215    71.67
5    150    50.00
6    262    87.33

In [22]:

16. Filter Failed Students
failed_students = df[df["Average"] < 50]

print(failed_students)

SyntaxError: invalid syntax (2528722988.py, line 1)

## Add Result Column

In [ ]:
df["Result"] = ["Pass" if avg >= 50 else "Fail" for avg in df["Average"]]
df

,Student_ID,Name,Math,Science,English,Attendance,Study_Hours,Total,Average,Result
0,1,Pratyaksh,85,88,78,92,5,251,83.67,Pass
1,2,Rahul,70,75,80,85,3,225,75.00,Pass
2,3,Sneha,90,95,92,96,6,277,92.33,Pass
3,4,Aman,95,92,88,90,7,275,91.67,Pass
4,5,Priya,60,75,80,80,4,215,71.67,Pass
5,6,Rohit,45,55,50,70,2,150,50.00,Pass
6,7,Neha,88,84,90,94,5,262,87.33,Pass
7,8,Karan,35,40,45,60,1,120,40.00,Fail

## Add Grade

In [ ]:
def assign_grade(avg):
    if avg >= 90:
        return "A+"
    elif avg >= 75:
        return "A"
    elif avg >= 60:
        return "B"
    elif avg >= 50:
        return "C"
    else:
        return "Fail"
df["Grade"] = df["Average"].apply(assign_grade)
df

,Student_ID,Name,Math,Science,English,Attendance,Study_Hours,Total,Average,Result,Grade
0,1,Pratyaksh,85,88,78,92,5,251,83.67,Pass,A
1,2,Rahul,70,75,80,85,3,225,75.00,Pass,A
2,3,Sneha,90,95,92,96,6,277,92.33,Pass,A+
3,4,Aman,95,92,88,90,7,275,91.67,Pass,A+
4,5,Priya,60,75,80,80,4,215,71.67,Pass,B
5,6,Rohit,45,55,50,70,2,150,50.00,Pass,C
6,7,Neha,88,84,90,94,5,262,87.33,Pass,A
7,8,Karan,35,40,45,60,1,120,40.00,Fail,Fail

##

## AI/ML Use Case: Separating Features and Target

In [ ]:
X = df[["Math", "Science", "English", "Attendance", "Study_Hours"]]
y = df["Result"]
print("Features:")
print(X)
print("Target:")
print(y)

Features:
   Math  Science  English  Attendance  Study_Hours
0    85       88       78          92            5
1    70       75       80          85            3
2    90       95       92          96            6
3    95       92       88          90            7
4    60       75       80          80            4
5    45       55       50          70            2
6    88       84       90          94            5
7    35       40       45          60            1
Target:
0    Pass
1    Pass
2    Pass
3    Pass
4    Pass
5    Pass
6    Pass
7    Fail
Name: Result, dtype: str

## Filter using `loc[]`

In [23]:
import pandas as pd

data = {
    "name": ["Rahul", "Aman", "Priya", "Sneha", "Karan", "Anjali", "Rohit"],
    "marks": [85, 72, 45, 91, 60, 88, 35],
    "attendance": [90, 80, 70, 95, 78, 92, 60],
    "study_hours": [5, 4, 3, 6, 2, 5, 1],
    "department": ["AI", "Data", "Web", "AI", "Data", "AI", "Web"]
}

df = pd.DataFrame(data)

print(df)

     name  marks  attendance  study_hours department
0   Rahul     85          90            5         AI
1    Aman     72          80            4       Data
2   Priya     45          70            3        Web
3   Sneha     91          95            6         AI
4   Karan     60          78            2       Data
5  Anjali     88          92            5         AI
6   Rohit     35          60            1        Web

In [25]:
result=df.loc[df["marks"]>=80, ["name","marks","department"]]
result

     name  marks department
0   Rahul     85         AI
3   Sneha     91         AI
5  Anjali     88         AI

## Sort data by one column

In [27]:
sort_df=df.sort_values(by="marks")
sort_df

     name  marks  attendance  study_hours department
6   Rohit     35          60            1        Web
2   Priya     45          70            3        Web
4   Karan     60          78            2       Data
1    Aman     72          80            4       Data
0   Rahul     85          90            5         AI
5  Anjali     88          92            5         AI
3   Sneha     91          95            6         AI

### In Descending order

In [29]:
sorted_dfd=df.sort_values(by="marks",ascending=False)
sorted_dfd

     name  marks  attendance  study_hours department
3   Sneha     91          95            6         AI
5  Anjali     88          92            5         AI
0   Rahul     85          90            5         AI
1    Aman     72          80            4       Data
4   Karan     60          78            2       Data
2   Priya     45          70            3        Web
6   Rohit     35          60            1        Web

## Sort multiple Columns

In [31]:
sortmul_df=df.sort_values(by=["department","marks"],ascending=[True,False])
sortmul_df

     name  marks  attendance  study_hours department
3   Sneha     91          95            6         AI
5  Anjali     88          92            5         AI
0   Rahul     85          90            5         AI
1    Aman     72          80            4       Data
4   Karan     60          78            2       Data
2   Priya     45          70            3        Web
6   Rohit     35          60            1        Web

## Create result column using conditions

In [32]:
def get_result(row):
    if row["marks"] >= 80 and row["attendance"] >= 85 and row["study_hours"] >= 5:
        return "Excellent"
    elif row["marks"] >= 50 and row["attendance"] >= 75:
        return "Good"
    else:
        return "Needs Improvement"


df["result"] = df.apply(get_result, axis=1)

print(df)

     name  marks  attendance  study_hours department             result
0   Rahul     85          90            5         AI          Excellent
1    Aman     72          80            4       Data               Good
2   Priya     45          70            3        Web  Needs Improvement
3   Sneha     91          95            6         AI          Excellent
4   Karan     60          78            2       Data               Good
5  Anjali     88          92            5         AI          Excellent
6   Rohit     35          60            1        Web  Needs Improvement