# day4_employee_analysis.py

In [1]:
import pandas as pd

## Tasks:

1. Create employee DataFrame
2. Add level column:
   Senior: experience >= 5 and salary >= 70000
   Mid-Level: experience >= 2 and salary >= 40000
   Junior: otherwise
3. Filter Senior, Mid-Level, and Junior employees
4. Sort employees by salary descending
5. Calculate average salary
6. Calculate highest salary
7. Calculate average experience
8. Count levels
9. Count departments
10. Save as day4_employee_analysis_report.csv

## Create employee dataframe

In [3]:
data = {
    "employee_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name": ["Amit", "Riya", "Karan", "Neha", "Vikas", "Anjali", "Rohit", "Priya", "Rahul", "Sneha"],
    "salary": [25000, 45000, 80000, 120000, 35000, 70000, 30000, 95000, 55000, 40000],
    "experience": [1, 3, 6, 8, 2, 5, 1, 7, 4, 2],
    "rating": [3, 4, 5, 5, 2, 4, 3, 5, 4, 3],
    "department": ["HR", "IT", "AI", "AI", "Sales", "Data", "IT", "Data", "Web", "HR"]
}
df=pd.DataFrame(data)
print(df)

   employee_id    name  salary  experience  rating department
0          101    Amit   25000           1       3         HR
1          102    Riya   45000           3       4         IT
2          103   Karan   80000           6       5         AI
3          104    Neha  120000           8       5         AI
4          105   Vikas   35000           2       2      Sales
5          106  Anjali   70000           5       4       Data
6          107   Rohit   30000           1       3         IT
7          108   Priya   95000           7       5       Data
8          109   Rahul   55000           4       4        Web
9          110   Sneha   40000           2       3         HR

## Add level coloumn

In [5]:
def get_level(row):
     if row["experience"]>=5 and row["salary"]>=70000:
          return "Senior"
     elif row["experience"]>=2 and row["salary"]>=40000:
          return "Mid-level"
     else:
          return "Junior"

df["level"]=df.apply(get_level,axis=1)
df

   employee_id    name  salary  experience  rating department      level
0          101    Amit   25000           1       3         HR     Junior
1          102    Riya   45000           3       4         IT  Mid-level
2          103   Karan   80000           6       5         AI     Senior
3          104    Neha  120000           8       5         AI     Senior
4          105   Vikas   35000           2       2      Sales     Junior
5          106  Anjali   70000           5       4       Data     Senior
6          107   Rohit   30000           1       3         IT     Junior
7          108   Priya   95000           7       5       Data     Senior
8          109   Rahul   55000           4       4        Web  Mid-level
9          110   Sneha   40000           2       3         HR  Mid-level

## 3. Filter Senior, Mid-Level, and Junior employees

In [8]:
fl_level=df.loc[df["level"]=="Senior",["employee_id","name"]]
print(fl_level)

   employee_id    name
2          103   Karan
3          104    Neha
5          106  Anjali
7          108   Priya

In [10]:
fl1_level=df.loc[df["level"]=="Mid-Level",["employee_id","name"]]
print(fl1_level)

Empty DataFrame
Columns: [employee_id, name]
Index: []

In [11]:
fl2_level=df.loc[df["level"]=="Junior",["employee_id","name"]]
print(fl2_level)

   employee_id   name
0          101   Amit
4          105  Vikas
6          107  Rohit

## 4. Sort employees by salary descending

In [14]:
sort=df.sort_values(by="salary",ascending=False)
sort

   employee_id    name  salary  experience  rating department      level
3          104    Neha  120000           8       5         AI     Senior
7          108   Priya   95000           7       5       Data     Senior
2          103   Karan   80000           6       5         AI     Senior
5          106  Anjali   70000           5       4       Data     Senior
8          109   Rahul   55000           4       4        Web  Mid-level
1          102    Riya   45000           3       4         IT  Mid-level
9          110   Sneha   40000           2       3         HR  Mid-level
4          105   Vikas   35000           2       2      Sales     Junior
6          107   Rohit   30000           1       3         IT     Junior
0          101    Amit   25000           1       3         HR     Junior

## 5. Calculate average salary

In [17]:
avg=df["salary"].mean()
print(avg)

59500.0

## 6. Calculate highest salary

In [20]:
max_sal=df["salary"].max()
print(max_sal)

120000

## 7. Calculate average experience

In [21]:
avg_exp=df["experience"].mean()
print(avg_exp)

3.9

## 8. Count levels

In [24]:
count_level=df["level"].sum()
print(count_level)

JuniorMid-levelSeniorSeniorJuniorSeniorJuniorSeniorMid-levelMid-level

## 9. Count departments

In [25]:
count_dept=df["department"].sum()
print(count_dept)

HRITAIAISalesDataITDataWebHR

## 10 Save to csv file

In [26]:
df.to_csv("day4_employee_analysis_report.csv", index=False)