# Ridge and Lasso Regression + Regularization

In [1]:
!pip install numpy pandas matplotlib seaborn scikit-learn

Requirement already satisfied: numpy in .\venv17\Lib\site-packages (2.4.6)
Requirement already satisfied: pandas in .\venv17\Lib\site-packages (3.0.3)
Requirement already satisfied: matplotlib in .\venv17\Lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in .\venv17\Lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in .\venv17\Lib\site-packages (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv17\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv17\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in .\venv17\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\venv17\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\venv17\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\venv17\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\venv17\Lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in .\venv17\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\venv17\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in .\venv17\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in .\venv17\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\venv17\Lib\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\venv17\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in .\venv17\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data={
     "study_hours": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "attendance": [40, 45, 50, 55, 60, 70, 75, 80, 85, 90, 95, 98],
    "previous_score": [35, 40, 45, 50, 55, 65, 70, 75, 82, 88, 92, 96],    
    "practice_questions": [10, 20, 30, 40, 50, 65, 75, 85, 95, 110, 125, 140],    
    "sleep_hours": [5, 5, 6, 6, 7, 7, 7, 8, 8, 8, 7, 7],    
    "mobile_usage_hours": [8, 7, 6, 5, 5, 4, 4, 3, 3, 2, 2, 1],    
    "final_marks": [38, 42, 48, 52, 58, 68, 72, 78, 84, 90, 94, 97]
}
df=pd.DataFrame(data)
df

,study_hours,attendance,previous_score,practice_questions,sleep_hours,mobile_usage_hours,final_marks
0,1,40,35,10,5,8,38
1,2,45,40,20,5,7,42
2,3,50,45,30,6,6,48
3,4,55,50,40,6,5,52
4,5,60,55,50,7,5,58
5,6,70,65,65,7,4,68
6,7,75,70,75,7,4,72
7,8,80,75,85,8,3,78
8,9,85,82,95,8,3,84
9,10,90,88,110,8,2,90
10,11,95,92,125,7,2,94
11,12,98,96,140,7,1,97

Feature

In [5]:
x=df.drop("final_marks",axis=1)
x

,study_hours,attendance,previous_score,practice_questions,sleep_hours,mobile_usage_hours
0,1,40,35,10,5,8
1,2,45,40,20,5,7
2,3,50,45,30,6,6
3,4,55,50,40,6,5
4,5,60,55,50,7,5
5,6,70,65,65,7,4
6,7,75,70,75,7,4
7,8,80,75,85,8,3
8,9,85,82,95,8,3
9,10,90,88,110,8,2
10,11,95,92,125,7,2
11,12,98,96,140,7,1

## Label

In [7]:
y=df["final_marks"]
y

0     38
1     42
2     48
3     52
4     58
5     68
6     72
7     78
8     84
9     90
10    94
11    97
Name: final_marks, dtype: int64

## Linear Pipeline regression

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

X_train,X_test,y_train,y_test=train_test_split(
     x,
     y,
     test_size=0.2,
     random_state=42
)
linear_pipeline = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("model", LinearRegression())
])
linear_pipeline.fit(X_train,y_train)
linear_pred=linear_pipeline.predict(X_test)
linear_mae=mean_absolute_error(y_test,linear_pred)
linear_mse=mean_squared_error(y_test,linear_pred)
linear_rmse=np.sqrt(linear_mse)
linear_r2 = r2_score(y_test, linear_pred)

print("Linear Regression")
print("MAE:", linear_mae)
print("RMSE:", linear_rmse)
print("R2:", linear_r2)

Linear Regression
MAE: 0.5686274509804056
RMSE: 0.8325832841396831
R2: 0.9989346389471894

## Ridge Pipeline regression

In [14]:
ridge_pipe=Pipeline(steps=[
     ("scaler",StandardScaler()),
     ("model",Ridge(alpha=1.0))
])
ridge_pipe.fit(X_train,y_train)
ridge_pred=ridge_pipe.predict(X_test)
ridge_mae=mean_absolute_error(y_test,ridge_pred)
ridge_mse=mean_squared_error(y_test,ridge_pred)
ridge_rmse=np.sqrt(ridge_mse)
ridge_r2=r2_score(y_test,ridge_pred)

print("Ridge Regression")
print("MAE:", ridge_mae)
print("MSE:", ridge_mse)
print("RMSE:", ridge_rmse)
print("R2:", ridge_r2)

Ridge Regression
MAE: 1.9617011185063784
MSE: 4.190957264776041
RMSE: 2.0471827629149386
R2: 0.9935589796135614

## Lasso Pipeline Regression

In [16]:
lasso_pipe=Pipeline(steps=[
     ("scaler",StandardScaler()),
     ("model",Lasso(alpha=1.0,max_iter=10000))
])
lasso_pipe.fit(X_train,y_train)
lasso_pred=lasso_pipe.predict(X_test)
lasso_mae=mean_absolute_error(y_test,lasso_pred)
lasso_mse=mean_squared_error(y_test,lasso_pred)
lasso_rmse=np.sqrt(lasso_mse)
lasso_r2=r2_score(y_test,lasso_pred)

print("Lasso Regression")
print("MAE:", lasso_mae)
print("MSE:", lasso_mse)
print("RMSE:", lasso_rmse)
print("R2:", lasso_r2)

Lasso Regression
MAE: 1.697710934465654
MSE: 3.1358256108601856
RMSE: 1.7708262508953796
R2: 0.9951805958849484

## Comparsion of Linear vs Ridge vs Lassso

In [18]:
results=pd.DataFrame({
     "Model": ["Linear Regression", "Ridge Regression", "Lasso Regression"],    
     "MAE": [linear_mae, ridge_mae, lasso_mae],
     "MSE": [linear_mse,ridge_mse,lasso_mse],   
     "RMSE": [linear_rmse, ridge_rmse, lasso_rmse],   
     "R2": [linear_r2, ridge_r2, lasso_r2]
})
results

               Model       MAE       MSE      RMSE        R2
0  Linear Regression  0.568627  0.693195  0.832583  0.998935
1   Ridge Regression  1.961701  4.190957  2.047183  0.993559
2   Lasso Regression  1.697711  3.135826  1.770826  0.995181

## Coeffiecients fo Linear and Ridge and lasso

In [23]:
linear_coef = linear_pipeline.named_steps["model"].coef_
ridge_coef = ridge_pipe.named_steps["model"].coef_
lasso_coef=lasso_pipe.named_steps["model"].coef_
coef_df = pd.DataFrame({    
     "Feature": x.columns,    
     "Linear": linear_coef.round(4),    
     "Ridge": ridge_coef.round(4),    
     "Lasso": lasso_coef.round(4)
})
coef_df

              Feature   Linear   Ridge   Lasso
0         study_hours  -9.7938  3.0726  0.0000
1          attendance  -0.9741  3.5165  9.9360
2      previous_score  17.3831  3.5656  6.1439
3  practice_questions   9.0896  3.1744  0.0000
4         sleep_hours   1.8325  1.5516  0.0000
5  mobile_usage_hours  -0.0000 -2.2360 -0.0000

## test different Alpha Values

### For Ridge

In [29]:
alpha_val=[0.001, 0.01, 0.1, 1, 10, 100]
results=[]
all_predictions=[]
for a in alpha_val:
     ridge_pipe=Pipeline(steps=[
          ("scaler",StandardScaler()),
          ("model",Ridge(alpha=a))
     ])
     ridge_pipe.fit(X_train,y_train)
     ridge_pred=ridge_pipe.predict(X_test)
     ridge_mae=mean_absolute_error(y_test,ridge_pred)
     ridge_mse=mean_squared_error(y_test,ridge_pred)
     ridge_rmse=np.sqrt(ridge_mse)
     ridge_r2=r2_score(y_test,ridge_pred)

     results.append({
          "Alpha_value":a,
          "MAE":ridge_mae,
          "MSE":ridge_mse,
          "RMSE":ridge_rmse,
          "R2_score":ridge_r2
     })
     pred_df = pd.DataFrame({
        "Alpha": a,
        "Actual": y_test.values,
        "Predicted": ridge_pred
    })
     all_predictions.append(pred_df)
result_df=pd.DataFrame(results)
print(result_df)
prediction_df = pd.concat(all_predictions, ignore_index=True)
print(prediction_df)

   Alpha_value        MAE         MSE       RMSE  R2_score
0        0.001   0.493125    0.505185   0.710763  0.999224
1        0.010   0.732248    0.556468   0.745968  0.999145
2        0.100   1.128882    1.317963   1.148026  0.997974
3        1.000   1.961701    4.190957   2.047183  0.993559
4       10.000   4.441513   23.958442   4.894736  0.963179
5      100.000  17.651571  313.689953  17.711295  0.517895
      Alpha  Actual  Predicted
0     0.001      94  92.788845
1     0.001      90  89.945536
2     0.001      38  37.786243
3     0.010      94  93.069794
4     0.010      90  89.398835
5     0.010      38  37.334627
6     0.100      94  92.721438
7     0.100      90  89.166371
8     0.100      38  36.725547
9     1.000      94  91.380719
10    1.000      90  88.802658
11    1.000      38  35.931519
12   10.000      94  87.016877
13   10.000      90  85.603622
14   10.000      38  39.945039
15  100.000      94  74.666924
16  100.000      90  74.212615
17  100.000      38  55.834251

### For Lasso

In [30]:
alpha_val=[0.001, 0.01, 0.1, 1, 10, 100]
results=[]
all_predictions=[]
for a in alpha_val:
     lasso_pipe=Pipeline(steps=[
          ("scaler",StandardScaler()),
          ("model",Lasso(alpha=a,max_iter=10000))
     ])
     lasso_pipe.fit(X_train,y_train)
     lasso_pred=lasso_pipe.predict(X_test)
     lasso_mae=mean_absolute_error(y_test,lasso_pred)
     lasso_mse=mean_squared_error(y_test,lasso_pred)
     lasso_rmse=np.sqrt(lasso_mse)
     lasso_r2=r2_score(y_test,lasso_pred)

     results.append({
          "Alpha_value":a,
          "MAE":lasso_mae,
          "MSE":lasso_mse,
          "RMSE":lasso_rmse,
          "R2_score":lasso_r2
     })
     pred_df = pd.DataFrame({
        "Alpha": a,
        "Actual": y_test.values,
        "Predicted": lasso_pred
    })
     all_predictions.append(pred_df)
result_df=pd.DataFrame(results)
print(result_df)
prediction_df = pd.concat(all_predictions, ignore_index=True)
print(prediction_df)

   Alpha_value        MAE         MSE       RMSE  R2_score
0        0.001   0.531735    0.475109   0.689281  0.999270
1        0.010   0.703668    0.540670   0.735303  0.999169
2        0.100   0.705192    0.524111   0.723955  0.999195
3        1.000   1.697711    3.135826   1.770826  0.995181
4       10.000  15.584612  243.883894  15.616782  0.625178
5      100.000  26.481481  706.086420  26.572287 -0.085174
      Alpha  Actual  Predicted
0     0.001      94  92.865905
1     0.001      90  89.897596
2     0.001      38  37.641295
3     0.010      94  93.104696
4     0.010      90  89.593988
5     0.010      38  37.190312
6     0.100      94  93.065764
7     0.100      90  89.438943
8     0.100      38  37.379717
9     1.000      94  92.173752
10    1.000      90  87.759917
11    1.000      38  39.026801
12   10.000      94  77.823175
13   10.000      90  75.826217
14   10.000      38  54.403228
15  100.000      94  66.555556
16  100.000      90  66.555556
17  100.000      38  66.555556

## Ridge/Lasso Features with Polynomial Features

In [32]:
from sklearn.preprocessing import PolynomialFeatures

poly_ridge_pipeline = Pipeline(steps=[
    ("poly", PolynomialFeatures(degree=3, include_bias=False)),
    ("scaler", StandardScaler()),
    ("model", Ridge(alpha=1.0))
])

poly_lasso_pipeline=Pipeline(steps=[
     ("poly", PolynomialFeatures(degree=3, include_bias=False)),
    ("scaler", StandardScaler()),
    ("model", Lasso(alpha=1.0,max_iter=10000))
])
poly_ridge_pipeline.fit(X_train, y_train)
poly_lasso_pipeline.fit(X_train, y_train)
poly_ridge_pred = poly_ridge_pipeline.predict(X_test)
poly_lasso_pred = poly_lasso_pipeline.predict(X_test)
poly_ridge_mae = mean_absolute_error(y_test, poly_ridge_pred)
poly_lasso_mae = mean_absolute_error(y_test, poly_lasso_pred)
print("Polynomial Ridge MAE:", poly_ridge_mae)
print("Polynomial Laaso MAE:", poly_lasso_mae)

Polynomial Ridge MAE: 0.8791361632112119
Polynomial Laaso MAE: 1.7821586120767374