# Handling values ing dropna() and fillna()

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in .\venv5\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in .\venv5\Lib\site-packages (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv5\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv5\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\venv5\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import numpy as np
import pandas as pd

## Messy dataset

In [4]:
data = {
    "student_id": [101, 102, 103, 104, 105, 106, 107],
    "name": ["Rahul", "Aman", None, "Sneha", "Karan", "Anjali", "Rohit"],
    "marks": [85, None, 45, 91, np.nan, 88, 35],
    "attendance": [90, 80, None, 95, 78, np.nan, 60],
    "study_hours": [5, 4, 3, None, 2, 5, np.nan],
    "subject": ["AI", "Data", "Web", "AI", None, "Data", "Web"]
}

In [5]:
df=pd.DataFrame(data)
df

   student_id    name  marks  attendance  study_hours subject
0         101   Rahul   85.0        90.0          5.0      AI
1         102    Aman    NaN        80.0          4.0    Data
2         103     NaN   45.0         NaN          3.0     Web
3         104   Sneha   91.0        95.0          NaN      AI
4         105   Karan    NaN        78.0          2.0     NaN
5         106  Anjali   88.0         NaN          5.0    Data
6         107   Rohit   35.0        60.0          NaN     Web

## Check NULL Values

In [ ]:
print(df.isnull())

   student_id   name  marks  attendance  study_hours  subject
0       False  False  False       False        False    False
1       False  False   True       False        False    False
2       False   True  False        True        False    False
3       False  False  False       False         True    False
4       False  False   True       False        False     True
5       False  False  False        True        False    False
6       False  False  False       False         True    False

In [7]:
print(df.isnull().sum())

student_id     0
name           1
marks          2
attendance     2
study_hours    2
subject        1
dtype: int64

## 4. `dropna()` - remove missing value

In [8]:
drop_df=df.dropna()
print(drop_df)

   student_id   name  marks  attendance  study_hours subject
0         101  Rahul   85.0        90.0          5.0      AI

## 5. Drop rows only when specific columns are missing

In [10]:
df_drop=df.dropna(subset=["name","marks"])
print(df_drop)

   student_id    name  marks  attendance  study_hours subject
0         101   Rahul   85.0        90.0          5.0      AI
3         104   Sneha   91.0        95.0          NaN      AI
5         106  Anjali   88.0         NaN          5.0    Data
6         107   Rohit   35.0        60.0          NaN     Web

## `fillna()`- fill missing data

### Fill text columns

In [12]:
df["name"]=df["name"].fillna("Unknown")
df["subject"]=df["subject"].fillna("Unknown")
df

   student_id     name  marks  attendance  study_hours  subject
0         101    Rahul   85.0        90.0          5.0       AI
1         102     Aman    NaN        80.0          4.0     Data
2         103  Unknown   45.0         NaN          3.0      Web
3         104    Sneha   91.0        95.0          NaN       AI
4         105    Karan    NaN        78.0          2.0  Unknown
5         106   Anjali   88.0         NaN          5.0     Data
6         107    Rohit   35.0        60.0          NaN      Web

### Fill numeric columns

In [14]:
df["marks"] = df["marks"].fillna(df["marks"].median())
df["attendance"] = df["attendance"].fillna(df["attendance"].mean())
df["study_hours"] = df["study_hours"].fillna(df["study_hours"].median())
df

   student_id     name  marks  attendance  study_hours  subject
0         101    Rahul   85.0        90.0          5.0       AI
1         102     Aman   85.0        80.0          4.0     Data
2         103  Unknown   45.0        80.6          3.0      Web
3         104    Sneha   91.0        95.0          4.0       AI
4         105    Karan   85.0        78.0          2.0  Unknown
5         106   Anjali   88.0        80.6          5.0     Data
6         107    Rohit   35.0        60.0          4.0      Web

In [15]:
df.to_csv("day5_null_handled_student_data.csv",index=False)