# Data Cleaning Basics

In [2]:
!pip install pandas numpy

Requirement already satisfied: pandas in .\venv5\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in .\venv5\Lib\site-packages (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv5\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv5\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\venv5\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## Messy Employee dataset

In [3]:
import pandas as pd
import numpy as np

data = {
    "employee_id": [101, 102, 103, 104, 105, 106, 106, 108, 109, 110],
    "name": ["Amit", "Riya", "Karan", "Neha", "Vikas", "Anjali", "Anjali", "Priya", "Rahul", None],
    "salary": [25000, 45000, 80000, 120000, -35000, 70000, 70000, None, 55000, 40000],
    "experience": [1, 3, 6, 8, 2, 5, 5, 7, "four", 2],
    "rating": [3, 4, 5, 5, 2, 4, 4, 5, 4, None],
    "department": ["HR", "IT", "AI", "ai", "Sales", "Data", "Data", "DATA", "Web", "HR"]
}

df = pd.DataFrame(data)

print(df)

   employee_id    name    salary experience  rating department
0          101    Amit   25000.0          1     3.0         HR
1          102    Riya   45000.0          3     4.0         IT
2          103   Karan   80000.0          6     5.0         AI
3          104    Neha  120000.0          8     5.0         ai
4          105   Vikas  -35000.0          2     2.0      Sales
5          106  Anjali   70000.0          5     4.0       Data
6          106  Anjali   70000.0          5     4.0       Data
7          108   Priya       NaN          7     5.0       DATA
8          109   Rahul   55000.0       four     4.0        Web
9          110     NaN   40000.0          2     NaN         HR

## Check missing values

In [4]:
print(df.isnull().sum())

employee_id    0
name           1
salary         1
experience     0
rating         1
department     0
dtype: int64

## Check Duplicate values

In [7]:
print(df.duplicated().sum())

1

if duplicate row exist, remove them:

In [8]:
print(df.drop_duplicates())

   employee_id    name    salary experience  rating department
0          101    Amit   25000.0          1     3.0         HR
1          102    Riya   45000.0          3     4.0         IT
2          103   Karan   80000.0          6     5.0         AI
3          104    Neha  120000.0          8     5.0         ai
4          105   Vikas  -35000.0          2     2.0      Sales
5          106  Anjali   70000.0          5     4.0       Data
7          108   Priya       NaN          7     5.0       DATA
8          109   Rahul   55000.0       four     4.0        Web
9          110     NaN   40000.0          2     NaN         HR

## Handle missing values

### Option 1 Drop rows with missing values

In [12]:
df_drop=df.dropna()
df_drop

   employee_id    name    salary experience  rating department
0          101    Amit   25000.0          1     3.0         HR
1          102    Riya   45000.0          3     4.0         IT
2          103   Karan   80000.0          6     5.0         AI
3          104    Neha  120000.0          8     5.0         ai
4          105   Vikas  -35000.0          2     2.0      Sales
5          106  Anjali   70000.0          5     4.0       Data
6          106  Anjali   70000.0          5     4.0       Data
8          109   Rahul   55000.0       four     4.0        Web

### Option 2: Filling Missing Values

In [19]:
df["name"] = df["name"].fillna("Unknown")
df["salary"] = df["salary"].fillna(df["salary"].mean()).round(2)
df["rating"] = df["rating"].fillna(df["rating"].mean()).round(2)
df

   employee_id     name     salary  experience  rating department
0          101     Amit   25000.00         1.0     3.0         HR
1          102     Riya   45000.00         3.0     4.0         IT
2          103    Karan   80000.00         6.0     5.0         AI
3          104     Neha  120000.00         8.0     5.0         ai
5          106   Anjali   70000.00         5.0     4.0       Data
6          106   Anjali   70000.00         5.0     4.0       Data
7          108    Priya   52222.22         7.0     5.0       DATA
8          109    Rahul   55000.00         NaN     4.0        Web
9          110  Unknown   40000.00         2.0     4.0         HR

## Fix invalid values

In [20]:
df = df[df["salary"] >= 0]
df

   employee_id     name     salary  experience  rating department
0          101     Amit   25000.00         1.0     3.0         HR
1          102     Riya   45000.00         3.0     4.0         IT
2          103    Karan   80000.00         6.0     5.0         AI
3          104     Neha  120000.00         8.0     5.0         ai
5          106   Anjali   70000.00         5.0     4.0       Data
6          106   Anjali   70000.00         5.0     4.0       Data
7          108    Priya   52222.22         7.0     5.0       DATA
8          109    Rahul   55000.00         NaN     4.0        Web
9          110  Unknown   40000.00         2.0     4.0         HR

## Fix Wring DataType

### Convert the value to Nan form

In [21]:
df["experience"] = pd.to_numeric(df["experience"], errors="coerce")
df

   employee_id     name     salary  experience  rating department
0          101     Amit   25000.00         1.0     3.0         HR
1          102     Riya   45000.00         3.0     4.0         IT
2          103    Karan   80000.00         6.0     5.0         AI
3          104     Neha  120000.00         8.0     5.0         ai
5          106   Anjali   70000.00         5.0     4.0       Data
6          106   Anjali   70000.00         5.0     4.0       Data
7          108    Priya   52222.22         7.0     5.0       DATA
8          109    Rahul   55000.00         NaN     4.0        Web
9          110  Unknown   40000.00         2.0     4.0         HR

### Fill missing experience

In [23]:
df["experience"] = df["experience"].fillna(df["experience"].median())
df

   employee_id     name     salary  experience  rating department
0          101     Amit   25000.00         1.0     3.0         HR
1          102     Riya   45000.00         3.0     4.0         IT
2          103    Karan   80000.00         6.0     5.0         AI
3          104     Neha  120000.00         8.0     5.0         ai
5          106   Anjali   70000.00         5.0     4.0       Data
6          106   Anjali   70000.00         5.0     4.0       Data
7          108    Priya   52222.22         7.0     5.0       DATA
8          109    Rahul   55000.00         5.0     4.0        Web
9          110  Unknown   40000.00         2.0     4.0         HR

## 8. Fix text Inconsistency

In [25]:
df["department"] = df["department"].str.upper()
df

   employee_id     name     salary  experience  rating department
0          101     Amit   25000.00         1.0     3.0         HR
1          102     Riya   45000.00         3.0     4.0         IT
2          103    Karan   80000.00         6.0     5.0         AI
3          104     Neha  120000.00         8.0     5.0         AI
5          106   Anjali   70000.00         5.0     4.0       DATA
6          106   Anjali   70000.00         5.0     4.0       DATA
7          108    Priya   52222.22         7.0     5.0       DATA
8          109    Rahul   55000.00         5.0     4.0        WEB
9          110  Unknown   40000.00         2.0     4.0         HR