# Type Conversion and Outlier Handling

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in .\venv5\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in .\venv5\Lib\site-packages (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv5\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv5\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\venv5\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd
import numpy as np

## Messy Dataset

In [6]:
data={
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "name": ["Rahul", "Aman", "Priya", "Sneha", "Karan", "Anjali", "Rohit", "Neha"],
    "marks": [85, "72", "sixty", 91, 120, 88, 35, -10],
    "attendance": [90, "80", 70, 95, 85, 150, -20, 75],
    "study_hours": [5, "4", 3, 6, 5, 50, 1, "two"],
    "subject": ["AI", "Data", "ai", "AI", "Ai", "DATA", "Web", "web"]
}

In [7]:
df=pd.DataFrame(data)
df

   student_id    name  marks attendance study_hours subject
0         101   Rahul     85         90           5      AI
1         102    Aman     72         80           4    Data
2         103   Priya  sixty         70           3      ai
3         104   Sneha     91         95           6      AI
4         105   Karan    120         85           5      Ai
5         106  Anjali     88        150          50    DATA
6         107   Rohit     35        -20           1     Web
7         108    Neha    -10         75         two     web

## COnvert the columns to numeric:

In [10]:
df["marks"]=pd.to_numeric(df["marks"],errors="coerce")
df["attendance"]=pd.to_numeric(df["attendance"],errors="coerce")
df["study_hours"]=pd.to_numeric(df["study_hours"],errors="coerce")
df

   student_id    name  marks  attendance  study_hours subject
0         101   Rahul   85.0          90          5.0      AI
1         102    Aman   72.0          80          4.0    Data
2         103   Priya    NaN          70          3.0      ai
3         104   Sneha   91.0          95          6.0      AI
4         105   Karan  120.0          85          5.0      Ai
5         106  Anjali   88.0         150         50.0    DATA
6         107   Rohit   35.0         -20          1.0     Web
7         108    Neha  -10.0          75          NaN     web

## Fill missing values after conversion

In [12]:
df["marks"] = df["marks"].fillna(df["marks"].median())
df["study_hours"] = df["study_hours"].fillna(df["study_hours"].median())
df

   student_id    name  marks  attendance  study_hours subject
0         101   Rahul   85.0          90          5.0      AI
1         102    Aman   72.0          80          4.0    Data
2         103   Priya   85.0          70          3.0      ai
3         104   Sneha   91.0          95          6.0      AI
4         105   Karan  120.0          85          5.0      Ai
5         106  Anjali   88.0         150         50.0    DATA
6         107   Rohit   35.0         -20          1.0     Web
7         108    Neha  -10.0          75          5.0     web

## Handle Invalide Range Values

### Method 1: Remove invalid rows

In [14]:
df = df[(df["marks"] >= 0) & (df["marks"] <= 100)]
df = df[(df["attendance"] >= 0) & (df["attendance"] <= 100)]
df = df[(df["study_hours"] >= 0) & (df["study_hours"] <= 12)]
df

   student_id   name  marks  attendance  study_hours subject
0         101  Rahul   85.0          90          5.0      AI
1         102   Aman   72.0          80          4.0    Data
2         103  Priya   85.0          70          3.0      ai
3         104  Sneha   91.0          95          6.0      AI

### Method 2: Clip Outliers

In [16]:
df["marks"] = df["marks"].clip(lower=0, upper=100)
df["attendance"] = df["attendance"].clip(lower=0, upper=100)
df["study_hours"] = df["study_hours"].clip(lower=0, upper=12)
df

   student_id   name  marks  attendance  study_hours subject
0         101  Rahul   85.0          90          5.0      AI
1         102   Aman   72.0          80          4.0    Data
2         103  Priya   85.0          70          3.0      ai
3         104  Sneha   91.0          95          6.0      AI

## 7. Standardize text column

In [18]:
df["subject"] = df["subject"].str.upper()
df

   student_id   name  marks  attendance  study_hours subject
0         101  Rahul   85.0          90          5.0      AI
1         102   Aman   72.0          80          4.0    DATA
2         103  Priya   85.0          70          3.0      AI
3         104  Sneha   91.0          95          6.0      AI

## IQR Method for Outliers

In [19]:
q1 = df["marks"].quantile(0.25)
q3 = df["marks"].quantile(0.75)

iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

df_without_outliers = df[
    (df["marks"] >= lower_bound) &
    (df["marks"] <= upper_bound)
]

print(df_without_outliers)

   student_id   name  marks  attendance  study_hours subject
0         101  Rahul   85.0          90          5.0      AI
2         103  Priya   85.0          70          3.0      AI
3         104  Sneha   91.0          95          6.0      AI