# day5_cleaned_student_data.csv

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in .\venv5\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in .\venv5\Lib\site-packages (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv5\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv5\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\venv5\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

## Messy Student Dataset

In [3]:
data = {
    "student_id": [101, 102, 103, 104, 105, 106, 106, 108, 109, 110],
    "name": ["Rahul", "Aman", "Priya", "Sneha", None, "Anjali", "Anjali", "Rohit", "Karan", "Neha"],
    "marks": [85, 72, None, 91, 120, 88, 88, 35, "sixty", 45],
    "attendance": [90, 80, 70, 95, 85, 92, 92, -10, 78, None],
    "study_hours": [5, 4, 3, 6, 5, 5, 5, 1, 2, None],
    "subject": ["AI", "Data", "ai", "AI", "Ai", "DATA", "DATA", "Web", "web", "Data"]
}

## Creation of DataFrame

In [4]:
df=pd.DataFrame(data)
df

   student_id    name  marks  attendance  study_hours subject
0         101   Rahul     85        90.0          5.0      AI
1         102    Aman     72        80.0          4.0    Data
2         103   Priya   None        70.0          3.0      ai
3         104   Sneha     91        95.0          6.0      AI
4         105     NaN    120        85.0          5.0      Ai
5         106  Anjali     88        92.0          5.0    DATA
6         106  Anjali     88        92.0          5.0    DATA
7         108   Rohit     35       -10.0          1.0     Web
8         109   Karan  sixty        78.0          2.0     web
9         110    Neha     45         NaN          NaN    Data

## Check Missing Values

In [5]:
print(df.isnull().sum())

student_id     0
name           1
marks          1
attendance     1
study_hours    1
subject        0
dtype: int64

## Check Duplicate value

In [6]:
print(df.duplicated().sum())

1

## Remove the duplicate value

In [8]:
print(df.drop_duplicates())
df

   student_id    name  marks  attendance  study_hours subject
0         101   Rahul     85        90.0          5.0      AI
1         102    Aman     72        80.0          4.0    Data
2         103   Priya   None        70.0          3.0      ai
3         104   Sneha     91        95.0          6.0      AI
4         105     NaN    120        85.0          5.0      Ai
5         106  Anjali     88        92.0          5.0    DATA
7         108   Rohit     35       -10.0          1.0     Web
8         109   Karan  sixty        78.0          2.0     web
9         110    Neha     45         NaN          NaN    Data

   student_id    name  marks  attendance  study_hours subject
0         101   Rahul     85        90.0          5.0      AI
1         102    Aman     72        80.0          4.0    Data
2         103   Priya   None        70.0          3.0      ai
3         104   Sneha     91        95.0          6.0      AI
4         105     NaN    120        85.0          5.0      Ai
5         106  Anjali     88        92.0          5.0    DATA
6         106  Anjali     88        92.0          5.0    DATA
7         108   Rohit     35       -10.0          1.0     Web
8         109   Karan  sixty        78.0          2.0     web
9         110    Neha     45         NaN          NaN    Data

## Handling missing values

### Option A Drop rows with missing values

In [9]:
df_drop=df.dropna()
df_drop

   student_id    name  marks  attendance  study_hours subject
0         101   Rahul     85        90.0          5.0      AI
1         102    Aman     72        80.0          4.0    Data
3         104   Sneha     91        95.0          6.0      AI
5         106  Anjali     88        92.0          5.0    DATA
6         106  Anjali     88        92.0          5.0    DATA
7         108   Rohit     35       -10.0          1.0     Web
8         109   Karan  sixty        78.0          2.0     web

### Option B Fill missing values

In [15]:
df["name"]=df["name"].fillna("Unknown")
df["attendance"]=df["attendance"].fillna(df["attendance"].mean()).round(2)
df["study_hours"]=df["study_hours"].fillna(df["study_hours"].mean()).round(2)

df

   student_id     name  marks  attendance  study_hours subject
0         101    Rahul     85       90.00          5.0      AI
1         102     Aman     72       80.00          4.0    Data
2         103    Priya   None       70.00          3.0      ai
3         104    Sneha     91       95.00          6.0      AI
4         105  Unknown    120       85.00          5.0      Ai
5         106   Anjali     88       92.00          5.0    DATA
6         106   Anjali     88       92.00          5.0    DATA
7         108    Rohit     35      -10.00          1.0     Web
8         109    Karan  sixty       78.00          2.0     web
9         110     Neha     45       74.67          4.0    Data

## Fix invalid values

In [16]:
df=df[df["attendance"]>=0]
df

   student_id     name  marks  attendance  study_hours subject
0         101    Rahul     85       90.00          5.0      AI
1         102     Aman     72       80.00          4.0    Data
2         103    Priya   None       70.00          3.0      ai
3         104    Sneha     91       95.00          6.0      AI
4         105  Unknown    120       85.00          5.0      Ai
5         106   Anjali     88       92.00          5.0    DATA
6         106   Anjali     88       92.00          5.0    DATA
8         109    Karan  sixty       78.00          2.0     web
9         110     Neha     45       74.67          4.0    Data

## Fix Wrong datatype

In [17]:
df["marks"]=pd.to_numeric(df["marks"],errors="coerce")
df

   student_id     name  marks  attendance  study_hours subject
0         101    Rahul   85.0       90.00          5.0      AI
1         102     Aman   72.0       80.00          4.0    Data
2         103    Priya    NaN       70.00          3.0      ai
3         104    Sneha   91.0       95.00          6.0      AI
4         105  Unknown  120.0       85.00          5.0      Ai
5         106   Anjali   88.0       92.00          5.0    DATA
6         106   Anjali   88.0       92.00          5.0    DATA
8         109    Karan    NaN       78.00          2.0     web
9         110     Neha   45.0       74.67          4.0    Data

In [18]:
df["marks"]=df["marks"].fillna(df["marks"].median())
df

   student_id     name  marks  attendance  study_hours subject
0         101    Rahul   85.0       90.00          5.0      AI
1         102     Aman   72.0       80.00          4.0    Data
2         103    Priya   88.0       70.00          3.0      ai
3         104    Sneha   91.0       95.00          6.0      AI
4         105  Unknown  120.0       85.00          5.0      Ai
5         106   Anjali   88.0       92.00          5.0    DATA
6         106   Anjali   88.0       92.00          5.0    DATA
8         109    Karan   88.0       78.00          2.0     web
9         110     Neha   45.0       74.67          4.0    Data

## Fix data inconsistency

In [19]:
df["subject"]=df["subject"].str.upper()
df

   student_id     name  marks  attendance  study_hours subject
0         101    Rahul   85.0       90.00          5.0      AI
1         102     Aman   72.0       80.00          4.0    DATA
2         103    Priya   88.0       70.00          3.0      AI
3         104    Sneha   91.0       95.00          6.0      AI
4         105  Unknown  120.0       85.00          5.0      AI
5         106   Anjali   88.0       92.00          5.0    DATA
6         106   Anjali   88.0       92.00          5.0    DATA
8         109    Karan   88.0       78.00          2.0     WEB
9         110     Neha   45.0       74.67          4.0    DATA

## save to csv file

In [20]:
df.to_csv("day5_cleaned_student_data.csv",index=False)