# day5_student_data_cleaning_project

In [20]:
!pip install pandas numpy

Requirement already satisfied: pandas in .\venv5\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in .\venv5\Lib\site-packages (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv5\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv5\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\venv5\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [21]:
import pandas as pd
import numpy as np

## Dataset

In [22]:
data = {
    "student_id": [101, 102, 103, 104, 105, 106, 106, 108, 109, 110],
    "name": ["Rahul", "Aman", "Priya", "Sneha", None, "Anjali", "Anjali", "Rohit", "Karan", "Neha"],
    "marks": [85, "72", "sixty", 91, 120, 88, 88, 35, -10, None],
    "attendance": [90, "80", 70, 95, 85, 92, 92, -20, 78, None],
    "study_hours": [5, "4", 3, 6, 5, 5, 5, 1, "two", None],
    "subject": ["AI", "Data", "ai", "AI", "Ai", "DATA", "DATA", "Web", "web", None]
}

df = pd.DataFrame(data)
df

   student_id    name  marks attendance study_hours subject
0         101   Rahul     85         90           5      AI
1         102    Aman     72         80           4    Data
2         103   Priya  sixty         70           3      ai
3         104   Sneha     91         95           6      AI
4         105     NaN    120         85           5      Ai
5         106  Anjali     88         92           5    DATA
6         106  Anjali     88         92           5    DATA
7         108   Rohit     35        -20           1     Web
8         109   Karan    -10         78         two     web
9         110    Neha   None       None        None     NaN

## Check missing values

In [23]:
print(df.isnull().sum())

student_id     0
name           1
marks          1
attendance     1
study_hours    1
subject        1
dtype: int64

## Check Duplicate Values

In [24]:
print(df.duplicated().sum())

1

Remove duplicate value

In [25]:
print(df.drop_duplicates())

   student_id    name  marks attendance study_hours subject
0         101   Rahul     85         90           5      AI
1         102    Aman     72         80           4    Data
2         103   Priya  sixty         70           3      ai
3         104   Sneha     91         95           6      AI
4         105     NaN    120         85           5      Ai
5         106  Anjali     88         92           5    DATA
7         108   Rohit     35        -20           1     Web
8         109   Karan    -10         78         two     web
9         110    Neha   None       None        None     NaN

## Handle missing values

### Option A drop rows

In [26]:
drop_df=df.dropna()
drop_df

   student_id    name  marks attendance study_hours subject
0         101   Rahul     85         90           5      AI
1         102    Aman     72         80           4    Data
2         103   Priya  sixty         70           3      ai
3         104   Sneha     91         95           6      AI
5         106  Anjali     88         92           5    DATA
6         106  Anjali     88         92           5    DATA
7         108   Rohit     35        -20           1     Web
8         109   Karan    -10         78         two     web

### Option B Filling Missing Value

In [27]:
df["name"]=df["name"].fillna("Unknown")
df["subject"]=df["subject"].fillna("Unknown")
df

   student_id     name  marks attendance study_hours  subject
0         101    Rahul     85         90           5       AI
1         102     Aman     72         80           4     Data
2         103    Priya  sixty         70           3       ai
3         104    Sneha     91         95           6       AI
4         105  Unknown    120         85           5       Ai
5         106   Anjali     88         92           5     DATA
6         106   Anjali     88         92           5     DATA
7         108    Rohit     35        -20           1      Web
8         109    Karan    -10         78         two      web
9         110     Neha   None       None        None  Unknown

## Fill numeric Value

In [28]:
df["marks"]=pd.to_numeric(df["marks"],errors="coerce")
df["attendance"]=pd.to_numeric(df["attendance"],errors="coerce")
df["study_hours"]=pd.to_numeric(df["study_hours"],errors="coerce")
df

   student_id     name  marks  attendance  study_hours  subject
0         101    Rahul   85.0        90.0          5.0       AI
1         102     Aman   72.0        80.0          4.0     Data
2         103    Priya    NaN        70.0          3.0       ai
3         104    Sneha   91.0        95.0          6.0       AI
4         105  Unknown  120.0        85.0          5.0       Ai
5         106   Anjali   88.0        92.0          5.0     DATA
6         106   Anjali   88.0        92.0          5.0     DATA
7         108    Rohit   35.0       -20.0          1.0      Web
8         109    Karan  -10.0        78.0          NaN      web
9         110     Neha    NaN         NaN          NaN  Unknown

In [30]:
df["marks"]=df["marks"].fillna(df["marks"].median())
df["attendance"]=df["attendance"].fillna(df["attendance"].median())
df["study_hours"]=df["study_hours"].fillna(df["study_hours"].median())
df

   student_id     name  marks  attendance  study_hours  subject
0         101    Rahul   85.0        90.0          5.0       AI
1         102     Aman   72.0        80.0          4.0     Data
2         103    Priya   86.5        70.0          3.0       ai
3         104    Sneha   91.0        95.0          6.0       AI
4         105  Unknown  120.0        85.0          5.0       Ai
5         106   Anjali   88.0        92.0          5.0     DATA
6         106   Anjali   88.0        92.0          5.0     DATA
7         108    Rohit   35.0       -20.0          1.0      Web
8         109    Karan  -10.0        78.0          5.0      web
9         110     Neha   86.5        85.0          5.0  Unknown

## Handle invalid range values

In [31]:
df["marks"] = df["marks"].clip(lower=0, upper=100)
df["attendance"] = df["attendance"].clip(lower=0, upper=100)
df["study_hours"] = df["study_hours"].clip(lower=0, upper=12)
df

   student_id     name  marks  attendance  study_hours  subject
0         101    Rahul   85.0        90.0          5.0       AI
1         102     Aman   72.0        80.0          4.0     Data
2         103    Priya   86.5        70.0          3.0       ai
3         104    Sneha   91.0        95.0          6.0       AI
4         105  Unknown  100.0        85.0          5.0       Ai
5         106   Anjali   88.0        92.0          5.0     DATA
6         106   Anjali   88.0        92.0          5.0     DATA
7         108    Rohit   35.0         0.0          1.0      Web
8         109    Karan    0.0        78.0          5.0      web
9         110     Neha   86.5        85.0          5.0  Unknown

## Standard Values

In [32]:
df["subject"]=df["subject"].str.upper()
df

   student_id     name  marks  attendance  study_hours  subject
0         101    Rahul   85.0        90.0          5.0       AI
1         102     Aman   72.0        80.0          4.0     DATA
2         103    Priya   86.5        70.0          3.0       AI
3         104    Sneha   91.0        95.0          6.0       AI
4         105  Unknown  100.0        85.0          5.0       AI
5         106   Anjali   88.0        92.0          5.0     DATA
6         106   Anjali   88.0        92.0          5.0     DATA
7         108    Rohit   35.0         0.0          1.0      WEB
8         109    Karan    0.0        78.0          5.0      WEB
9         110     Neha   86.5        85.0          5.0  UNKNOWN

Save to CSV

In [33]:
df.to_csv("day5_student_data_cleaning_project.csv",index=False)