# day5_type_outlier_student_cleaned

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in .\venv5\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in .\venv5\Lib\site-packages (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv5\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv5\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\venv5\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

## Messy Dataset

In [3]:
data = {
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name": ["Rahul", "Aman", "Priya", "Sneha", "Karan", "Anjali", "Rohit", "Neha", "Vikas", "Riya"],
    "marks": [85, "72", "sixty", 91, 120, 88, 35, -10, "95", 67],
    "attendance": [90, "80", 70, 95, 85, 150, -20, 75, "ninety", 82],
    "study_hours": [5, "4", 3, 6, 5, 50, 1, "two", 7, -3],
    "subject": ["AI", "Data", "ai", "AI", "Ai", "DATA", "Web", "web", "data", "WEB"]
}

In [5]:
df=pd.DataFrame(data)
df

   student_id    name  marks attendance study_hours subject
0         101   Rahul     85         90           5      AI
1         102    Aman     72         80           4    Data
2         103   Priya  sixty         70           3      ai
3         104   Sneha     91         95           6      AI
4         105   Karan    120         85           5      Ai
5         106  Anjali     88        150          50    DATA
6         107   Rohit     35        -20           1     Web
7         108    Neha    -10         75         two     web
8         109   Vikas     95     ninety           7    data
9         110    Riya     67         82          -3     WEB

## Convert Columns to numeric

In [9]:
df["marks"]=pd.to_numeric(df["marks"],errors="coerce")
df["attendance"]=pd.to_numeric(df["attendance"],errors="coerce")
df["study_hours"]=pd.to_numeric(df["study_hours"],errors="coerce")
df

   student_id    name  marks  attendance  study_hours subject
0         101   Rahul   85.0        90.0          5.0      AI
1         102    Aman   72.0        80.0          4.0    Data
2         103   Priya    NaN        70.0          3.0      ai
3         104   Sneha   91.0        95.0          6.0      AI
4         105   Karan  120.0        85.0          5.0      Ai
5         106  Anjali   88.0       150.0         50.0    DATA
6         107   Rohit   35.0       -20.0          1.0     Web
7         108    Neha  -10.0        75.0          NaN     web
8         109   Vikas   95.0         NaN          7.0    data
9         110    Riya   67.0        82.0         -3.0     WEB

## Filling missing values

In [12]:
df["marks"]=df["marks"].fillna(df["marks"].median())
df["attendance"]=df["attendance"].fillna(df["attendance"].median())
df["stuyd_hours"]=df["study_hours"].fillna(df["study_hours"].median())
df

   student_id    name  marks  attendance  study_hours subject  stuyd_hours
0         101   Rahul   85.0        90.0          5.0      AI          5.0
1         102    Aman   72.0        80.0          4.0    Data          4.0
2         103   Priya   85.0        70.0          3.0      ai          3.0
3         104   Sneha   91.0        95.0          6.0      AI          6.0
4         105   Karan  120.0        85.0          5.0      Ai          5.0
5         106  Anjali   88.0       150.0         50.0    DATA         50.0
6         107   Rohit   35.0       -20.0          1.0     Web          1.0
7         108    Neha  -10.0        75.0          NaN     web          5.0
8         109   Vikas   95.0        82.0          7.0    data          7.0
9         110    Riya   67.0        82.0         -3.0     WEB         -3.0

## handle invalid range values

### Remove Invalid rows:

In [15]:
df=df[(df["marks"]>=0)& (df["marks"]<=100)]
df=df[(df["attendance"]>=0)& (df["attendance"]<=100)]
df=df[(df["study_hours"]>=0)& (df["study_hours"]<=100)]
df

   student_id   name  marks  attendance  study_hours subject  stuyd_hours
0         101  Rahul   85.0        90.0          5.0      AI          5.0
1         102   Aman   72.0        80.0          4.0    Data          4.0
2         103  Priya   85.0        70.0          3.0      ai          3.0
3         104  Sneha   91.0        95.0          6.0      AI          6.0
8         109  Vikas   95.0        82.0          7.0    data          7.0

### Clip Outliers

In [16]:
df["marks"] = df["marks"].clip(lower=0, upper=100)
df["attendance"] = df["attendance"].clip(lower=0, upper=100)
df["study_hours"] = df["study_hours"].clip(lower=0, upper=12)
df

   student_id   name  marks  attendance  study_hours subject  stuyd_hours
0         101  Rahul   85.0        90.0          5.0      AI          5.0
1         102   Aman   72.0        80.0          4.0    Data          4.0
2         103  Priya   85.0        70.0          3.0      ai          3.0
3         104  Sneha   91.0        95.0          6.0      AI          6.0
8         109  Vikas   95.0        82.0          7.0    data          7.0

## Convert subject to uppercase

In [17]:
df["subject"]=df["subject"].str.upper()
df

   student_id   name  marks  attendance  study_hours subject  stuyd_hours
0         101  Rahul   85.0        90.0          5.0      AI          5.0
1         102   Aman   72.0        80.0          4.0    DATA          4.0
2         103  Priya   85.0        70.0          3.0      AI          3.0
3         104  Sneha   91.0        95.0          6.0      AI          6.0
8         109  Vikas   95.0        82.0          7.0    DATA          7.0

In [18]:
df.to_csv("day5_type_outlier_student_cleaned.csv",index=False)