## Data Preprocessing

In [3]:
!pip install numpy pandas matplotlib seaborn

Requirement already satisfied: numpy in .\venv16\Lib\site-packages (2.4.6)
Requirement already satisfied: pandas in .\venv16\Lib\site-packages (3.0.3)
Requirement already satisfied: matplotlib in .\venv16\Lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in .\venv16\Lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv16\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv16\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in .\venv16\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\venv16\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\venv16\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\venv16\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\venv16\Lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in .\venv16\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\venv16\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in .\venv16\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = {
    "student_id": [101, 102, 103, 104, 105, 105, 106, 107],
    "study_hours": [5, 2, np.nan, 8, 6, 6, 1, 7],
    "attendance": [80, 45, 60, np.nan, 75, 75, 30, 85],
    "previous_score": [70, 40, 55, 90, np.nan, np.nan, 35, 88],
    "study_method": ["Online", "Offline", "Online", "Offline", np.nan, np.nan, "Offline", "Online"],
    "final_marks": [75, 42, 58, 92, 70, 70, 38, 90]
}

In [6]:
df=pd.DataFrame(data)
df

,student_id,study_hours,attendance,previous_score,study_method,final_marks
0,101,5.0,80.0,70.0,Online,75
1,102,2.0,45.0,40.0,Offline,42
2,103,NaN,60.0,55.0,Online,58
3,104,8.0,NaN,90.0,Offline,92
4,105,6.0,75.0,NaN,NaN,70
5,105,6.0,75.0,NaN,NaN,70
6,106,1.0,30.0,35.0,Offline,38
7,107,7.0,85.0,88.0,Online,90

In [7]:
df.head()

,student_id,study_hours,attendance,previous_score,study_method,final_marks
0,101,5.0,80.0,70.0,Online,75
1,102,2.0,45.0,40.0,Offline,42
2,103,NaN,60.0,55.0,Online,58
3,104,8.0,NaN,90.0,Offline,92
4,105,6.0,75.0,NaN,NaN,70

In [8]:
df.tail()

,student_id,study_hours,attendance,previous_score,study_method,final_marks
3,104,8.0,NaN,90.0,Offline,92
4,105,6.0,75.0,NaN,NaN,70
5,105,6.0,75.0,NaN,NaN,70
6,106,1.0,30.0,35.0,Offline,38
7,107,7.0,85.0,88.0,Online,90

In [10]:
df.shape

(8, 6)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      8 non-null      int64
 1   study_hours     7 non-null      float64
 2   attendance      7 non-null      float64
 3   previous_score  6 non-null      float64
 4   study_method    6 non-null      str
 5   final_marks     8 non-null      int64
dtypes: float64(3), int64(2), str(1)
memory usage: 516.0 bytes

In [13]:
df.describe()

       student_id  study_hours  attendance  previous_score  final_marks
count     8.00000     7.000000    7.000000        6.000000     8.000000
mean    104.12500     5.000000   64.285714       63.000000    66.875000
std       2.03101     2.581989   20.295437       23.579652    19.938745
min     101.00000     1.000000   30.000000       35.000000    38.000000
25%     102.75000     3.500000   52.500000       43.750000    54.000000
50%     104.50000     6.000000   75.000000       62.500000    70.000000
75%     105.25000     6.500000   77.500000       83.500000    78.750000
max     107.00000     8.000000   85.000000       90.000000    92.000000

In [16]:
print(df.columns)

Index(['student_id', 'study_hours', 'attendance', 'previous_score',
       'study_method', 'final_marks'],
      dtype='str')

In [18]:
df.isnull()

,student_id,study_hours,attendance,previous_score,study_method,final_marks
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,True,False,False,False,False
3,False,False,True,False,False,False
4,False,False,False,True,True,False
5,False,False,False,True,True,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False

In [19]:
df.isnull().sum()

student_id        0
study_hours       1
attendance        1
previous_score    2
study_method      2
final_marks       0
dtype: int64

In [22]:
miss_per=df.isnull().mean()*100
miss_per

student_id         0.0
study_hours       12.5
attendance        12.5
previous_score    25.0
study_method      25.0
final_marks        0.0
dtype: float64

In [23]:
df_drop=df.dropna()
df_drop

,student_id,study_hours,attendance,previous_score,study_method,final_marks
0,101,5.0,80.0,70.0,Online,75
1,102,2.0,45.0,40.0,Offline,42
6,106,1.0,30.0,35.0,Offline,38
7,107,7.0,85.0,88.0,Online,90

In [25]:
df_dro_col=df.drop("study_hours",axis=1)
df_dro_col

   student_id  attendance  previous_score study_method  final_marks
0         101        80.0            70.0       Online           75
1         102        45.0            40.0      Offline           42
2         103        60.0            55.0       Online           58
3         104         NaN            90.0      Offline           92
4         105        75.0             NaN          NaN           70
5         105        75.0             NaN          NaN           70
6         106        30.0            35.0      Offline           38
7         107        85.0            88.0       Online           90

In [27]:
df["study_hours"]=df["study_hours"].fillna(df["study_hours"].mean())
df

,student_id,study_hours,attendance,previous_score,study_method,final_marks
0,101,5.0,80.0,70.0,Online,75
1,102,2.0,45.0,40.0,Offline,42
2,103,5.0,60.0,55.0,Online,58
3,104,8.0,NaN,90.0,Offline,92
4,105,6.0,75.0,NaN,NaN,70
5,105,6.0,75.0,NaN,NaN,70
6,106,1.0,30.0,35.0,Offline,38
7,107,7.0,85.0,88.0,Online,90

In [29]:
df["attendance"]=df["attendance"].fillna(df["attendance"].median())
df

,student_id,study_hours,attendance,previous_score,study_method,final_marks
0,101,5.0,80.0,70.0,Online,75
1,102,2.0,45.0,40.0,Offline,42
2,103,5.0,60.0,55.0,Online,58
3,104,8.0,75.0,90.0,Offline,92
4,105,6.0,75.0,NaN,NaN,70
5,105,6.0,75.0,NaN,NaN,70
6,106,1.0,30.0,35.0,Offline,38
7,107,7.0,85.0,88.0,Online,90

In [32]:
df["study_method"]=df["study_method"].fillna(df["study_method"].mode()[0])
df

,student_id,study_hours,attendance,previous_score,study_method,final_marks
0,101,5.0,80.0,70.0,Online,75
1,102,2.0,45.0,40.0,Offline,42
2,103,5.0,60.0,55.0,Online,58
3,104,8.0,75.0,90.0,Offline,92
4,105,6.0,75.0,NaN,Offline,70
5,105,6.0,75.0,NaN,Offline,70
6,106,1.0,30.0,35.0,Offline,38
7,107,7.0,85.0,88.0,Online,90

In [34]:
df["study_method"]=df["study_method"].fillna("Unknown")
df

,student_id,study_hours,attendance,previous_score,study_method,final_marks
0,101,5.0,80.0,70.0,Online,75
1,102,2.0,45.0,40.0,Offline,42
2,103,5.0,60.0,55.0,Online,58
3,104,8.0,75.0,90.0,Offline,92
4,105,6.0,75.0,NaN,Offline,70
5,105,6.0,75.0,NaN,Offline,70
6,106,1.0,30.0,35.0,Offline,38
7,107,7.0,85.0,88.0,Online,90

In [36]:
df["prev_sc_miss"]=df["previous_score"].isnull().astype(int)
df

,student_id,study_hours,attendance,previous_score,study_method,final_marks,prev_sc_miss
0,101,5.0,80.0,70.0,Online,75,0
1,102,2.0,45.0,40.0,Offline,42,0
2,103,5.0,60.0,55.0,Online,58,0
3,104,8.0,75.0,90.0,Offline,92,0
4,105,6.0,75.0,NaN,Offline,70,1
5,105,6.0,75.0,NaN,Offline,70,1
6,106,1.0,30.0,35.0,Offline,38,0
7,107,7.0,85.0,88.0,Online,90,0

In [38]:
df["previous_score"]=df["previous_score"].fillna(df["previous_score"].median())
df

,student_id,study_hours,attendance,previous_score,study_method,final_marks,prev_sc_miss
0,101,5.0,80.0,70.0,Online,75,0
1,102,2.0,45.0,40.0,Offline,42,0
2,103,5.0,60.0,55.0,Online,58,0
3,104,8.0,75.0,90.0,Offline,92,0
4,105,6.0,75.0,62.5,Offline,70,1
5,105,6.0,75.0,62.5,Offline,70,1
6,106,1.0,30.0,35.0,Offline,38,0
7,107,7.0,85.0,88.0,Online,90,0

In [40]:
!pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in .\venv16\Lib\site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.22.1-py3-none-any.whl (454 kB)
Using cached scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn

   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   ---------------------------------------- 5/5 [scikit-learn]

Successfully installed joblib-1.5.3 narwhals-2.22.1 scikit-learn-1.9.0 scipy-1.17.1 threadpoolctl-3.6.0

In [39]:
from sklearn.impute import SimpleImputer

ModuleNotFoundError: No module named 'sklearn'