# Encoding Categorical Variables: Label Encoding and One-Hot Encoding

In [4]:
!pip install numpy pandas matplotlib seaborn

Requirement already satisfied: numpy in .\venv16\Lib\site-packages (2.4.6)
Requirement already satisfied: pandas in .\venv16\Lib\site-packages (3.0.3)
Requirement already satisfied: matplotlib in .\venv16\Lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in .\venv16\Lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv16\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv16\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in .\venv16\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\venv16\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\venv16\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\venv16\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\venv16\Lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in .\venv16\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\venv16\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in .\venv16\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
data = {
    "cgpa": [8.5, 6.2, 7.8, 5.9, 9.1, 8.0],
    "branch": ["CSE", "ECE", "CSE", "ME", "ECE", "CSE"],
    "internship": ["Yes", "No", "Yes", "No", "Yes", "No"],
    "skill_level": ["Advanced", "Beginner", "Intermediate", "Beginner", "Advanced", "Intermediate"],
    "placed": ["Yes", "No", "Yes", "No", "Yes", "Yes"]
}
df=pd.DataFrame(data)
df

   cgpa branch internship   skill_level placed
0   8.5    CSE        Yes      Advanced    Yes
1   6.2    ECE         No      Beginner     No
2   7.8    CSE        Yes  Intermediate    Yes
3   5.9     ME         No      Beginner     No
4   9.1    ECE        Yes      Advanced    Yes
5   8.0    CSE         No  Intermediate    Yes

In [7]:
df["internship_en"]=df["internship"].map({
     "No":0,
     "Yes":1
})
df[["internship","internship_en"]]

  internship  internship_en
0        Yes              1
1         No              0
2        Yes              1
3         No              0
4        Yes              1
5         No              0

In [8]:
skill_order={
     "Beginner":0,
     "Intermediate":1,
     "Advanced":2
}
df["skill_level_en"]=df["skill_level"].map(skill_order)
df[["skill_level","skill_level_en"]]

    skill_level  skill_level_en
0      Advanced               2
1      Beginner               0
2  Intermediate               1
3      Beginner               0
4      Advanced               2
5  Intermediate               1

In [9]:
branch_encoded = pd.get_dummies(df["branch"], prefix="branch", dtype=int)
branch_encoded

   branch_CSE  branch_ECE  branch_ME
0           1           0          0
1           0           1          0
2           1           0          0
3           0           0          1
4           0           1          0
5           1           0          0

In [15]:
df_encoded = pd.concat([df, branch_encoded], axis=1)
df_encoded

,cgpa,branch,internship,skill_level,placed,internship_en,skill_level_en,branch_CSE,branch_ECE,branch_ME
0,8.5,CSE,Yes,Advanced,Yes,1,2,1,0,0
1,6.2,ECE,No,Beginner,No,0,0,0,1,0
2,7.8,CSE,Yes,Intermediate,Yes,1,1,1,0,0
3,5.9,ME,No,Beginner,No,0,0,0,0,1
4,9.1,ECE,Yes,Advanced,Yes,1,2,0,1,0
5,8.0,CSE,No,Intermediate,Yes,0,1,1,0,0

In [16]:
df_encoded = df_encoded.drop("branch", axis=1)
df_encoded

,cgpa,internship,skill_level,placed,internship_en,skill_level_en,branch_CSE,branch_ECE,branch_ME
0,8.5,Yes,Advanced,Yes,1,2,1,0,0
1,6.2,No,Beginner,No,0,0,0,1,0
2,7.8,Yes,Intermediate,Yes,1,1,1,0,0
3,5.9,No,Beginner,No,0,0,0,0,1
4,9.1,Yes,Advanced,Yes,1,2,0,1,0
5,8.0,No,Intermediate,Yes,0,1,1,0,0

In [18]:
df_encoded = pd.get_dummies(
    df,
    columns=["branch"],
    dtype=int
)

df_encoded

,cgpa,internship,skill_level,placed,internship_en,skill_level_en,branch_CSE,branch_ECE,branch_ME
0,8.5,Yes,Advanced,Yes,1,2,1,0,0
1,6.2,No,Beginner,No,0,0,0,1,0
2,7.8,Yes,Intermediate,Yes,1,1,1,0,0
3,5.9,No,Beginner,No,0,0,0,0,1
4,9.1,Yes,Advanced,Yes,1,2,0,1,0
5,8.0,No,Intermediate,Yes,0,1,1,0,0

In [19]:
df["placed_encoded"] = df["placed"].map({
    "No": 0,
    "Yes": 1
})

df[["placed", "placed_encoded"]]

  placed  placed_encoded
0    Yes               1
1     No               0
2    Yes               1
3     No               0
4    Yes               1
5    Yes               1

In [22]:
x= df[["cgpa", "internship_en", "skill_level_en"]]
y = df["placed_encoded"]
print(x)
print(y)

   cgpa  internship_en  skill_level_en
0   8.5              1               2
1   6.2              0               0
2   7.8              1               1
3   5.9              0               0
4   9.1              1               2
5   8.0              0               1
0    1
1    0
2    1
3    0
4    1
5    1
Name: placed_encoded, dtype: int64

In [23]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in .\venv16\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in .\venv16\Lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in .\venv16\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in .\venv16\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\venv16\Lib\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\venv16\Lib\site-packages (from scikit-learn) (3.6.0)

In [25]:
from sklearn.preprocessing import OneHotEncoder

data = {
    "branch": ["CSE", "ECE", "CSE", "ME", "ECE", "CSE"]
}

df_branch = pd.DataFrame(data)

encoder = OneHotEncoder(sparse_output=False)

encoded_array = encoder.fit_transform(df_branch[["branch"]])

encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoder.get_feature_names_out(["branch"])
)
encoded_df

   branch_CSE  branch_ECE  branch_ME
0         1.0         0.0        0.0
1         0.0         1.0        0.0
2         1.0         0.0        0.0
3         0.0         0.0        1.0
4         0.0         1.0        0.0
5         1.0         0.0        0.0